((TypeDefinition
  (Inductive
   ((set ()
     (NonGadt
      ((Empty ())
       (Node
        ((Apply (PathName ((path ()) (base set))) ())
         (Apply (PathName ((path ()) (base Z))) ())
         (Apply (PathName ((path ()) (base set))) ())))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name empty) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base set))) ()))))
      (Constructor ((path ()) (base Empty)) ()))))))
 (Value
  ((is_rec (New true))
   (cases
    ((((name member) (typ_vars ())
       (args
        ((x (Apply (PathName ((path ()) (base Z))) ()))
         (s (Apply (PathName ((path ()) (base set))) ()))))
       (typ ((Apply (PathName ((path ()) (base bool))) ()))))
      (Match (Variable (PathName ((path ()) (base s))))
       (((Constructor ((path ()) (base Empty)) ())
         (Constructor ((path ()) (base false)) ()))
        ((Constructor ((path ()) (base Node))
          ((Variable s1) (Variable y) (Variable s2)))
         (IfThenElse
          (Apply (Variable (PathName ((path (OCaml Stdlib)) (base lt))))
           ((Variable (PathName ((path ()) (base x))))
            (Variable (PathName ((path ()) (base y))))))
          (Apply (Variable (PathName ((path ()) (base member))))
           ((Variable (PathName ((path ()) (base x))))
            (Variable (PathName ((path ()) (base s1))))))
          (IfThenElse
           (Apply (Variable (PathName ((path (OCaml Stdlib)) (base lt))))
            ((Variable (PathName ((path ()) (base y))))
             (Variable (PathName ((path ()) (base x))))))
           (Apply (Variable (PathName ((path ()) (base member))))
            ((Variable (PathName ((path ()) (base x))))
             (Variable (PathName ((path ()) (base s2))))))
           (Constructor ((path ()) (base true)) ())))))))))))
 (Value
  ((is_rec (New true))
   (cases
    ((((name insert) (typ_vars ())
       (args
        ((x (Apply (PathName ((path ()) (base Z))) ()))
         (s (Apply (PathName ((path ()) (base set))) ()))))
       (typ ((Apply (PathName ((path ()) (base set))) ()))))
      (Match (Variable (PathName ((path ()) (base s))))
       (((Constructor ((path ()) (base Empty)) ())
         (Constructor ((path ()) (base Node))
          ((Constructor ((path ()) (base Empty)) ())
           (Variable (PathName ((path ()) (base x))))
           (Constructor ((path ()) (base Empty)) ()))))
        ((Constructor ((path ()) (base Node))
          ((Variable s1) (Variable y) (Variable s2)))
         (IfThenElse
          (Apply (Variable (PathName ((path (OCaml Stdlib)) (base lt))))
           ((Variable (PathName ((path ()) (base x))))
            (Variable (PathName ((path ()) (base y))))))
          (Constructor ((path ()) (base Node))
           ((Apply (Variable (PathName ((path ()) (base insert))))
             ((Variable (PathName ((path ()) (base x))))
              (Variable (PathName ((path ()) (base s1))))))
            (Variable (PathName ((path ()) (base y))))
            (Variable (PathName ((path ()) (base s2))))))
          (IfThenElse
           (Apply (Variable (PathName ((path (OCaml Stdlib)) (base lt))))
            ((Variable (PathName ((path ()) (base y))))
             (Variable (PathName ((path ()) (base x))))))
           (Constructor ((path ()) (base Node))
            ((Variable (PathName ((path ()) (base s1))))
             (Variable (PathName ((path ()) (base y))))
             (Apply (Variable (PathName ((path ()) (base insert))))
              ((Variable (PathName ((path ()) (base x))))
               (Variable (PathName ((path ()) (base s2))))))))
           (Variable (PathName ((path ()) (base s)))))))))))))))
