((Value
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars (A B)) (args ((x (Variable A)) (y (Variable B))))
       (typ ((Variable A))))
      (Variable ((path ()) (base x))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base Z)) ()))))
      (Apply (Variable ((path ()) (base f)))
       ((Constant (Int 12)) (Constant (Int 3))))))))))
