((Value
  ((is_rec (New false))
   (cases
    ((((name t0) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base unit))) ()))))
      (Constructor ((path ()) (base tt)) ()))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name t1) (typ_vars ()) (args ())
       (typ
        ((Tuple
          ((Apply (PathName ((path ()) (base ascii))) ())
           (Apply (PathName ((path ()) (base string))) ()))))))
      (Tuple ((Constant (Char c)) (Constant (String one)))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name t2) (typ_vars ()) (args ())
       (typ
        ((Tuple
          ((Apply (PathName ((path ()) (base Z))) ())
           (Apply (PathName ((path ()) (base Z))) ())
           (Apply (PathName ((path ()) (base Z))) ())
           (Apply (PathName ((path ()) (base bool))) ())
           (Apply (PathName ((path ()) (base bool))) ()))))))
      (Tuple
       ((Constant (Int 1)) (Constant (Int 2)) (Constant (Int 3))
        (Constructor ((path ()) (base false)) ())
        (Constructor ((path ()) (base true)) ()))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars (A)) (args ((x (Variable A))))
       (typ ((Tuple ((Variable A) (Variable A))))))
      (Tuple
       ((Variable (PathName ((path ()) (base x))))
        (Variable (PathName ((path ()) (base x)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name t3) (typ_vars ()) (args ())
       (typ
        ((Tuple
          ((Apply (PathName ((path ()) (base Z))) ())
           (Apply (PathName ((path ()) (base Z))) ()))))))
      (Apply (Variable (PathName ((path ()) (base f))))
       ((Constant (Int 12))))))))))
