((Value (Known tests/ex02.ml ((line 3)) ((line 3)))
  ((is_rec (New false))
   (cases
    ((((name t0) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base unit))) (depth 1)) ()))))
      (Constructor ((path_name ((path ()) (base tt))) (depth 1)) ()))))))
 (Value (Known tests/ex02.ml ((line 5)) ((line 5)))
  ((is_rec (New false))
   (cases
    ((((name t1) (typ_vars ()) (args ())
       (typ
        ((Tuple
          ((Apply ((path_name ((path ()) (base ascii))) (depth 1)) ())
           (Apply ((path_name ((path ()) (base string))) (depth 1)) ()))))))
      (Tuple ((Constant (Char c)) (Constant (String one)))))))))
 (Value (Known tests/ex02.ml ((line 7)) ((line 7)))
  ((is_rec (New false))
   (cases
    ((((name t2) (typ_vars ()) (args ())
       (typ
        ((Tuple
          ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ())
           (Apply ((path_name ((path ()) (base Z))) (depth 1)) ())
           (Apply ((path_name ((path ()) (base Z))) (depth 1)) ())
           (Apply ((path_name ((path ()) (base bool))) (depth 1)) ())
           (Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))))
      (Tuple
       ((Constant (Int 1)) (Constant (Int 2)) (Constant (Int 3))
        (Constructor ((path_name ((path ()) (base false))) (depth 1)) ())
        (Constructor ((path_name ((path ()) (base true))) (depth 1)) ()))))))))
 (Value (Known tests/ex02.ml ((line 9)) ((line 9)))
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars (A)) (args ((x (Variable A))))
       (typ ((Tuple ((Variable A) (Variable A))))))
      (Tuple
       ((Variable ((path_name ((path ()) (base x))) (depth 0)))
        (Variable ((path_name ((path ()) (base x))) (depth 0))))))))))
 (Value (Known tests/ex02.ml ((line 11)) ((line 11)))
  ((is_rec (New false))
   (cases
    ((((name t3) (typ_vars ()) (args ())
       (typ
        ((Tuple
          ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ())
           (Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
      (Apply (Variable ((path_name ((path ()) (base f))) (depth 0)))
       ((Constant (Int 12))))))))))
