3
((),
  Value (@., non_rec, n1, [ ], [ ], Some Type (Z/1)) =
    Let 4 (@., non_rec, m, [ ], [ ], None) =
      Constant (4, Int(12)) in
    Let 5 (@., non_rec, n1, [ ], [ ], None) =
      Variable (5, m/0) in
    Variable (6, n1/0))

8
((),
  Value (@., non_rec, n2, [ ], [ ], Some Type (Z/1)) =
    Let 9
      (@., non_rec, p1, [ A691; A705; A708 ],
        [ (c, ((A705/0 -> (A708/0 -> A705/0)) -> A691/0)) ], Some A691/0) =
      Apply
        (9, Variable (9, c/0),
          [ Function (9, x, Function (9, y, Variable (9, x/0))) ]) in
    Let 10
      (@., non_rec, c, [ A718 ],
        [ (f, (Type (Z/1) -> (Type (Z/1) -> A718/0))) ], Some A718/0) =
      Apply
        (10, Variable (10, f/0),
          [ Constant (10, Int(12)); Constant (10, Int(23)) ]) in
    Apply (11, Variable (11, p1/0), [ Variable (11, c/0) ]))
