((Value
  (Known ((file_name tests/ex04.ml) (line 3))
   ((file_name tests/ex04.ml) (line 3)))
  ((is_rec (New false))
   (cases
    ((((name u) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base unit))) (depth 1)) ()))))
      (Constructor
       (Known ((file_name tests/ex04.ml) (line 3))
        ((file_name tests/ex04.ml) (line 3)))
       ((path_name ((path ()) (base tt))) (depth 1)) ()))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 5))
   ((file_name tests/ex04.ml) (line 5)))
  ((is_rec (New false))
   (cases
    ((((name l1) (typ_vars (A)) (args ())
       (typ
        ((Apply ((path_name ((path ()) (base list))) (depth 1))
          ((Variable A))))))
      (Constructor
       (Known ((file_name tests/ex04.ml) (line 5))
        ((file_name tests/ex04.ml) (line 5)))
       ((path_name ((path ()) (base []))) (depth 1)) ()))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 7))
   ((file_name tests/ex04.ml) (line 7)))
  ((is_rec (New false))
   (cases
    ((((name l2) (typ_vars ()) (args ())
       (typ
        ((Apply ((path_name ((path ()) (base list))) (depth 1))
          ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
      (Constructor
       (Known ((file_name tests/ex04.ml) (line 7))
        ((file_name tests/ex04.ml) (line 7)))
       ((path_name ((path ()) (base cons))) (depth 1))
       ((Constant
         (Known ((file_name tests/ex04.ml) (line 7))
          ((file_name tests/ex04.ml) (line 7)))
         (Int 1))
        (Constructor
         (Known ((file_name tests/ex04.ml) (line 7))
          ((file_name tests/ex04.ml) (line 7)))
         ((path_name ((path ()) (base []))) (depth 1)) ()))))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 9))
   ((file_name tests/ex04.ml) (line 9)))
  ((is_rec (New false))
   (cases
    ((((name l3) (typ_vars ()) (args ())
       (typ
        ((Apply ((path_name ((path ()) (base list))) (depth 1))
          ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
      (Constructor
       (Known ((file_name tests/ex04.ml) (line 9))
        ((file_name tests/ex04.ml) (line 9)))
       ((path_name ((path ()) (base cons))) (depth 1))
       ((Constant
         (Known ((file_name tests/ex04.ml) (line 9))
          ((file_name tests/ex04.ml) (line 9)))
         (Int 1))
        (Constructor
         (Known ((file_name tests/ex04.ml) (line 9))
          ((file_name tests/ex04.ml) (line 9)))
         ((path_name ((path ()) (base cons))) (depth 1))
         ((Constant
           (Known ((file_name tests/ex04.ml) (line 9))
            ((file_name tests/ex04.ml) (line 9)))
           (Int 5))
          (Constructor
           (Known ((file_name tests/ex04.ml) (line 9))
            ((file_name tests/ex04.ml) (line 9)))
           ((path_name ((path ()) (base cons))) (depth 1))
           ((Constant
             (Known ((file_name tests/ex04.ml) (line 9))
              ((file_name tests/ex04.ml) (line 9)))
             (Int 7))
            (Constructor
             (Known ((file_name tests/ex04.ml) (line 9))
              ((file_name tests/ex04.ml) (line 9)))
             ((path_name ((path ()) (base cons))) (depth 1))
             ((Constant
               (Known ((file_name tests/ex04.ml) (line 9))
                ((file_name tests/ex04.ml) (line 9)))
               (Int 32))
              (Constructor
               (Known ((file_name tests/ex04.ml) (line 9))
                ((file_name tests/ex04.ml) (line 9)))
               ((path_name ((path ()) (base cons))) (depth 1))
               ((Constant
                 (Known ((file_name tests/ex04.ml) (line 9))
                  ((file_name tests/ex04.ml) (line 9)))
                 (Int 15))
                (Constructor
                 (Known ((file_name tests/ex04.ml) (line 9))
                  ((file_name tests/ex04.ml) (line 9)))
                 ((path_name ((path ()) (base []))) (depth 1)) ()))))))))))))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 11))
   ((file_name tests/ex04.ml) (line 11)))
  ((is_rec (New false))
   (cases
    ((((name o1) (typ_vars (A)) (args ())
       (typ
        ((Apply ((path_name ((path ()) (base option))) (depth 1))
          ((Variable A))))))
      (Constructor
       (Known ((file_name tests/ex04.ml) (line 11))
        ((file_name tests/ex04.ml) (line 11)))
       ((path_name ((path ()) (base None))) (depth 1)) ()))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 13))
   ((file_name tests/ex04.ml) (line 13)))
  ((is_rec (New false))
   (cases
    ((((name o2) (typ_vars ()) (args ())
       (typ
        ((Apply ((path_name ((path ()) (base option))) (depth 1))
          ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
      (Constructor
       (Known ((file_name tests/ex04.ml) (line 13))
        ((file_name tests/ex04.ml) (line 13)))
       ((path_name ((path ()) (base Some))) (depth 1))
       ((Constant
         (Known ((file_name tests/ex04.ml) (line 13))
          ((file_name tests/ex04.ml) (line 13)))
         (Int 12)))))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 15))
   ((file_name tests/ex04.ml) (line 15)))
  ((is_rec (New false))
   (cases
    ((((name c) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base ascii))) (depth 1)) ()))))
      (Constant
       (Known ((file_name tests/ex04.ml) (line 15))
        ((file_name tests/ex04.ml) (line 15)))
       (Char g)))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 17))
   ((file_name tests/ex04.ml) (line 17)))
  ((is_rec (New false))
   (cases
    ((((name s1) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base string))) (depth 1)) ()))))
      (Constant
       (Known ((file_name tests/ex04.ml) (line 17))
        ((file_name tests/ex04.ml) (line 17)))
       (String bla)))))))
 (Value
  (Known ((file_name tests/ex04.ml) (line 19))
   ((file_name tests/ex04.ml) (line 19)))
  ((is_rec (New false))
   (cases
    ((((name s2) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base string))) (depth 1)) ()))))
      (Constant
       (Known ((file_name tests/ex04.ml) (line 19))
        ((file_name tests/ex04.ml) (line 19)))
       (String "\""))))))))
