((Value
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base Z)) ()))))
      (Match
       (Tuple
        ((Constructor ((path ()) (base cons))
          ((Constant (Int 1))
           (Constructor ((path ()) (base cons))
            ((Constant (Int 2)) (Constructor ((path ()) (base [])) ())))))
         (Constructor ((path ()) (base false)) ())))
       (((Tuple
          ((Constructor ((path ()) (base cons))
            ((Variable x)
             (Constructor ((path ()) (base cons))
              (Any (Constructor ((path ()) (base [])) ())))))
           (Constructor ((path ()) (base true)) ())))
         (Variable ((path ()) (base x))))
        ((Tuple
          ((Constructor ((path ()) (base cons))
            (Any
             (Constructor ((path ()) (base cons))
              ((Variable y) (Constructor ((path ()) (base [])) ())))))
           (Constructor ((path ()) (base false)) ())))
         (Variable ((path ()) (base y))))
        (Any (Constant (Int 0)))))))))))
