3
(Value
  (non_rec, @.,
    [
      ((n, [ ], [ ], Some Type (Z/0)),
        Match
          (3,
            Tuple
              (3,
                Constructor
                  (3, cons/0, Constant (3, Int(1)),
                    Constructor
                      (3, cons/0, Constant (3, Int(2)),
                        Constructor (3, []/0))),
                Constructor (3, false/0)),
            [
              (Tuple
                (Constructor
                  (cons/0, x,
                    Constructor
                      (cons/0,
                        Any,
                        Constructor
                          ([]/0))),
                  Constructor (true/0)),
                Variable (4, x/0));
              (Tuple
                (Constructor
                  (cons/0, Any,
                    Constructor
                      (cons/0,
                        y,
                        Constructor
                          ([]/0))),
                  Constructor (false/0)),
                Variable (5, y/0));
              (Any, Constant (6, Int(0)))
            ]))
    ]))
