3
Value
  (non_rec,
    [
      ((n, [ ], [ ], Some Type (Z/1)),
        Match
          (3,
            Tuple
              (3,
                Constructor
                  (3, cons/1, Constant (3, Int(1)),
                    Constructor
                      (3, cons/1, Constant (3, Int(2)),
                        Constructor (3, []/1))),
                Constructor (3, false/1)),
            [
              (Tuple
                (Constructor
                  (cons/1, x,
                    Constructor
                      (cons/1,
                        Any,
                        Constructor
                          ([]/1))),
                  Constructor (true/1)),
                Variable (4, x/0));
              (Tuple
                (Constructor
                  (cons/1, Any,
                    Constructor
                      (cons/1,
                        y,
                        Constructor
                          ([]/1))),
                  Constructor (false/1)),
                Variable (5, y/0));
              (Any, Constant (6, Int(0)))
            ]))
    ])
