3
(Value
  (rec, @.,
    [
      ((map_rec, [ A; B ],
        [ (counter, Type (nat/0)); (f, (A -> B)); (l, Type (list/0, A)) ],
        Some Type (list/0, B)),
        Match
          (?, Variable (?, counter/0),
            [
              (Constructor (O/0),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated/0),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S/0, counter),
                Match
                  (4, Variable (4, l/0),
                    [
                      (Constructor
                        ([]/0),
                        Constructor
                          (5,
                            []/0));
                      (Constructor
                        (cons/0,
                          x,
                          xs),
                        Constructor
                          (6,
                            cons/0,
                            Apply
                              (6,
                                Variable
                                  (6,
                                    f/0),
                                [
                                  Variable
                                    (6,
                                      x/0)
                                ]),
                            Apply
                              (6,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        map_rec/0),
                                    [
                                      Variable
                                        (?,
                                          counter/0)
                                    ]),
                                [
                                  Variable
                                    (6,
                                      f/0);
                                  Variable
                                    (6,
                                      xs/0)
                                ])))
                    ]))
            ]))
    ]))

3
(Value
  (non_rec, @.,
    [
      ((map, [ A; B ], [ (f, (A -> B)); (l, Type (list/0, A)) ],
        Some Type (list/0, B)),
        Apply
          (?, Variable (?, map_rec/0),
            [
              Apply (?, Variable (?, read_counter/0), [ Tuple (?) ]);
              Variable (?, f/0);
              Variable (?, l/0)
            ]))
    ]))

8
(Value
  (rec, @.,
    [
      ((fold_rec, [ A; B ],
        [
          (counter, Type (nat/0));
          (f, (A -> (B -> A)));
          (a, A);
          (l, Type (list/0, B))
        ], Some A),
        Match
          (?, Variable (?, counter/0),
            [
              (Constructor (O/0),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated/0),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S/0, counter),
                Match
                  (9, Variable (9, l/0),
                    [
                      (Constructor
                        ([]/0),
                        Variable
                          (10,
                            a/0));
                      (Constructor
                        (cons/0,
                          x,
                          xs),
                        Apply
                          (11,
                            Apply
                              (?,
                                Variable
                                  (?,
                                    fold_rec/0),
                                [
                                  Variable
                                    (?,
                                      counter/0)
                                ]),
                            [
                              Variable
                                (11,
                                  f/0);
                              Apply
                                (11,
                                  Variable
                                    (11,
                                      f/0),
                                  [
                                    Variable
                                      (11,
                                        a/0);
                                    Variable
                                      (11,
                                        x/0)
                                  ]);
                              Variable
                                (11,
                                  xs/0)
                            ]))
                    ]))
            ]))
    ]))

8
(Value
  (non_rec, @.,
    [
      ((fold, [ A; B ], [ (f, (A -> (B -> A))); (a, A); (l, Type (list/0, B)) ],
        Some A),
        Apply
          (?, Variable (?, fold_rec/0),
            [
              Apply (?, Variable (?, read_counter/0), [ Tuple (?) ]);
              Variable (?, f/0);
              Variable (?, a/0);
              Variable (?, l/0)
            ]))
    ]))

13
(Value
  (non_rec, @.,
    [
      ((l, [ ], [ ], Some Type (list/0, Type (Z/0))),
        Constructor
          (13, cons/0, Constant (13, Int(5)),
            Constructor
              (13, cons/0, Constant (13, Int(6)),
                Constructor
                  (13, cons/0, Constant (13, Int(7)),
                    Constructor
                      (13, cons/0, Constant (13, Int(2)),
                        Constructor (13, []/0))))))
    ]))

15
(Value
  (non_rec, @.,
    [
      ((n, [ A ],
        [
          (incr, (Type (Z/0) -> A));
          (plus, (Type (Z/0) -> (A -> Type (Z/0))))
        ], Some Type (Z/0)),
        Apply
          (16, Variable (16, fold/0),
            [
              Function
                (16, x,
                  Function
                    (16,
                      y,
                      Apply
                        (16,
                          Variable
                            (16,
                              plus/0),
                          [
                            Variable
                              (16,
                                x/0);
                            Variable
                              (16,
                                y/0)
                          ])));
              Constant (16, Int(0));
              Apply
                (16, Variable (16, map/0),
                  [
                    Variable
                      (16,
                        incr/0);
                    Variable
                      (16,
                        l/0)
                  ])
            ]))
    ]))
