((Value
  ((is_rec (New true))
   (cases
    ((((name map) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Variable B)))
         (l
          (Apply ((path_name ((path ()) (base list))) (depth 1))
           ((Variable A))))))
       (typ
        ((Apply ((path_name ((path ()) (base list))) (depth 1))
          ((Variable B))))))
      (Match (Variable ((path_name ((path ()) (base l))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base []))) (depth 1)) ())
         (Constructor ((path_name ((path ()) (base []))) (depth 1)) ()))
        ((Constructor ((path_name ((path ()) (base cons))) (depth 1))
          ((Variable x) (Variable xs)))
         (Constructor ((path_name ((path ()) (base cons))) (depth 1))
          ((Apply (Variable ((path_name ((path ()) (base f))) (depth 0)))
            ((Variable ((path_name ((path ()) (base x))) (depth 0)))))
           (Apply (Variable ((path_name ((path ()) (base map))) (depth 0)))
            ((Variable ((path_name ((path ()) (base f))) (depth 0)))
             (Variable ((path_name ((path ()) (base xs))) (depth 0)))))))))))))))
 (Value
  ((is_rec (New true))
   (cases
    ((((name fold) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Arrow (Variable B) (Variable A))))
         (a (Variable A))
         (l
          (Apply ((path_name ((path ()) (base list))) (depth 1))
           ((Variable B))))))
       (typ ((Variable A))))
      (Match (Variable ((path_name ((path ()) (base l))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base []))) (depth 1)) ())
         (Variable ((path_name ((path ()) (base a))) (depth 0))))
        ((Constructor ((path_name ((path ()) (base cons))) (depth 1))
          ((Variable x) (Variable xs)))
         (Apply (Variable ((path_name ((path ()) (base fold))) (depth 0)))
          ((Variable ((path_name ((path ()) (base f))) (depth 0)))
           (Apply (Variable ((path_name ((path ()) (base f))) (depth 0)))
            ((Variable ((path_name ((path ()) (base a))) (depth 0)))
             (Variable ((path_name ((path ()) (base x))) (depth 0)))))
           (Variable ((path_name ((path ()) (base xs))) (depth 0)))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name l) (typ_vars ()) (args ())
       (typ
        ((Apply ((path_name ((path ()) (base list))) (depth 1))
          ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
      (Constructor ((path_name ((path ()) (base cons))) (depth 1))
       ((Constant (Int 5))
        (Constructor ((path_name ((path ()) (base cons))) (depth 1))
         ((Constant (Int 6))
          (Constructor ((path_name ((path ()) (base cons))) (depth 1))
           ((Constant (Int 7))
            (Constructor ((path_name ((path ()) (base cons))) (depth 1))
             ((Constant (Int 2))
              (Constructor ((path_name ((path ()) (base []))) (depth 1)) ()))))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars (A))
       (args
        ((incr
          (Arrow (Apply ((path_name ((path ()) (base Z))) (depth 1)) ())
           (Variable A)))
         (plus
          (Arrow (Apply ((path_name ((path ()) (base Z))) (depth 1)) ())
           (Arrow (Variable A)
            (Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path ()) (base fold))) (depth 0)))
       ((Function x
         (Function y
          (Apply (Variable ((path_name ((path ()) (base plus))) (depth 0)))
           ((Variable ((path_name ((path ()) (base x))) (depth 0)))
            (Variable ((path_name ((path ()) (base y))) (depth 0)))))))
        (Constant (Int 0))
        (Apply (Variable ((path_name ((path ()) (base map))) (depth 0)))
         ((Variable ((path_name ((path ()) (base incr))) (depth 0)))
          (Variable ((path_name ((path ()) (base l))) (depth 0)))))))))))))
