Inductive 't1':
  ([ ],
    [
      ('C1', [ Type ('Z') ]);
      ('C2', [ Type ('bool'); Type ('Z') ]);
      ('C3', [ ])
    ])

((),
  Value (non_rec, 'n', [ ], [ ], Some Type ('t1')) =
    Constructor (?, 'C2', Constructor (?, 'false'), Constant (?, Int(3))))

((),
  Value (non_rec, 'm', [ ], [ ], Some Type ('bool')) =
    Match
      (?, Variable (?, 'n'),
        [
          (Constructor ('C2', 'b', Any), Variable (?, 'b'));
          (Any, Constructor (?, 'true'))
        ]))

Inductive 't2':
  ([ 'a' ], [ ('D1', [ ]); ('D2', [ 'a'; Type ('t2', 'a') ]) ])

((),
  Value
    (rec, 'of_list_rec', [ 'A' ],
      [ ('counter', Type ('nat')); ('l', Type ('list', 'A')) ],
      Some Type ('t2', 'A')) =
    Match
      (?, Variable (?, 'counter'),
        [
          (Nat(0),
            Apply (?, Variable (?, 'not_terminated'), Variable (?, 'tt')));
          (Constructor ('S', 'counter'),
            Match
              (?, Variable (?, 'l'),
                [
                  (Constructor ('[]'),
                    Constructor
                      (?,
                        'D1'));
                  (Constructor ('cons', 'x', 'xs'),
                    Constructor
                      (?,
                        'D2',
                        Variable
                          (?,
                            'x'),
                        Apply
                          (?,
                            Apply
                              (?,
                                Variable
                                  (?,
                                    'of_list_rec'),
                                Variable
                                  (?,
                                    'counter')),
                            Variable
                              (?,
                                'xs'))))
                ]))
        ]))

((),
  Value
    (non_rec, 'of_list', [ 'A' ], [ ('l', Type ('list', 'A')) ],
      Some Type ('t2', 'A')) =
    Let ? (non_rec, 'counter', [ ], [ ], None) =
      Apply (?, Variable (?, 'read_counter'), Variable (?, 'tt')) in
    Apply
      (?, Apply (?, Variable (?, 'of_list_rec'), Variable (?, 'counter')),
        Variable (?, 'l')))

((),
  Value
    (rec, 'sum_rec', [ ],
      [ ('counter', Type ('nat')); ('l', Type ('t2', Type ('Z'))) ],
      Some Type ('Z')) =
    Match
      (?, Variable (?, 'counter'),
        [
          (Nat(0),
            Apply (?, Variable (?, 'not_terminated'), Variable (?, 'tt')));
          (Constructor ('S', 'counter'),
            Match
              (?, Variable (?, 'l'),
                [
                  (Constructor ('D1'),
                    Constant
                      (?,
                        Int(0)));
                  (Constructor ('D2', 'x', 'xs'),
                    Apply
                      (?,
                        Apply
                          (?,
                            Variable
                              (?,
                                'Z.add'),
                            Variable
                              (?,
                                'x')),
                        Apply
                          (?,
                            Apply
                              (?,
                                Variable
                                  (?,
                                    'sum_rec'),
                                Variable
                                  (?,
                                    'counter')),
                            Variable
                              (?,
                                'xs'))))
                ]))
        ]))

((),
  Value
    (non_rec, 'sum', [ ], [ ('l', Type ('t2', Type ('Z'))) ], Some Type ('Z')) =
    Let ? (non_rec, 'counter', [ ], [ ], None) =
      Apply (?, Variable (?, 'read_counter'), Variable (?, 'tt')) in
    Apply
      (?, Apply (?, Variable (?, 'sum_rec'), Variable (?, 'counter')),
        Variable (?, 'l')))

((),
  Value (non_rec, 's', [ ], [ ], Some Type ('Z')) =
    Apply
      (?, Variable (?, 'sum'),
        Apply
          (?, Variable (?, 'of_list'),
            Constructor
              (?, 'cons', Constant (?, Int(5)),
                Constructor
                  (?, 'cons', Constant (?, Int(7)),
                    Constructor
                      (?, 'cons', Constant (?, Int(3)), Constructor (?, '[]')))))))
