((TypeDefinition
  (Known ((file_name tests/ex08.ml) (line 3))
   ((file_name tests/ex08.ml) (line 6)))
  (Inductive t1 ()
   ((C1 ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ())))
    (C2
     ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ())
      (Apply ((path_name ((path ()) (base Z))) (depth 1)) ())))
    (C3 ()))))
 (Value
  (Known ((file_name tests/ex08.ml) (line 8))
   ((file_name tests/ex08.ml) (line 8)))
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base t1))) (depth 0)) ()))))
      (Constructor
       (Known ((file_name tests/ex08.ml) (line 8))
        ((file_name tests/ex08.ml) (line 8)))
       ((path_name ((path ()) (base C2))) (depth 0))
       ((Constructor
         (Known ((file_name tests/ex08.ml) (line 8))
          ((file_name tests/ex08.ml) (line 8)))
         ((path_name ((path ()) (base false))) (depth 1)) ())
        (Constant
         (Known ((file_name tests/ex08.ml) (line 8))
          ((file_name tests/ex08.ml) (line 8)))
         (Int 3)))))))))
 (Value
  (Known ((file_name tests/ex08.ml) (line 10))
   ((file_name tests/ex08.ml) (line 12)))
  ((is_rec (New false))
   (cases
    ((((name m) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))
      (Match
       (Known ((file_name tests/ex08.ml) (line 10))
        ((file_name tests/ex08.ml) (line 12)))
       (Variable
        (Known ((file_name tests/ex08.ml) (line 10))
         ((file_name tests/ex08.ml) (line 10)))
        ((path_name ((path ()) (base n))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base C2))) (depth 0))
          ((Variable b) Any))
         (Variable
          (Known ((file_name tests/ex08.ml) (line 11))
           ((file_name tests/ex08.ml) (line 11)))
          ((path_name ((path ()) (base b))) (depth 0))))
        (Any
         (Constructor
          (Known ((file_name tests/ex08.ml) (line 12))
           ((file_name tests/ex08.ml) (line 12)))
          ((path_name ((path ()) (base true))) (depth 1)) ())))))))))
 (TypeDefinition
  (Known ((file_name tests/ex08.ml) (line 14))
   ((file_name tests/ex08.ml) (line 16)))
  (Inductive t2 (a)
   ((D1 ())
    (D2
     ((Variable a)
      (Apply ((path_name ((path ()) (base t2))) (depth 0)) ((Variable a))))))))
 (Value
  (Known ((file_name tests/ex08.ml) (line 18))
   ((file_name tests/ex08.ml) (line 21)))
  ((is_rec (New true))
   (cases
    ((((name of_list) (typ_vars (A))
       (args
        ((l
          (Apply ((path_name ((path ()) (base list))) (depth 1))
           ((Variable A))))))
       (typ
        ((Apply ((path_name ((path ()) (base t2))) (depth 0)) ((Variable A))))))
      (Match
       (Known ((file_name tests/ex08.ml) (line 19))
        ((file_name tests/ex08.ml) (line 21)))
       (Variable
        (Known ((file_name tests/ex08.ml) (line 19))
         ((file_name tests/ex08.ml) (line 19)))
        ((path_name ((path ()) (base l))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base []))) (depth 1)) ())
         (Constructor
          (Known ((file_name tests/ex08.ml) (line 20))
           ((file_name tests/ex08.ml) (line 20)))
          ((path_name ((path ()) (base D1))) (depth 0)) ()))
        ((Constructor ((path_name ((path ()) (base cons))) (depth 1))
          ((Variable x) (Variable xs)))
         (Constructor
          (Known ((file_name tests/ex08.ml) (line 21))
           ((file_name tests/ex08.ml) (line 21)))
          ((path_name ((path ()) (base D2))) (depth 0))
          ((Variable
            (Known ((file_name tests/ex08.ml) (line 21))
             ((file_name tests/ex08.ml) (line 21)))
            ((path_name ((path ()) (base x))) (depth 0)))
           (Apply
            (Known ((file_name tests/ex08.ml) (line 21))
             ((file_name tests/ex08.ml) (line 21)))
            (Variable
             (Known ((file_name tests/ex08.ml) (line 21))
              ((file_name tests/ex08.ml) (line 21)))
             ((path_name ((path ()) (base of_list))) (depth 0)))
            ((Variable
              (Known ((file_name tests/ex08.ml) (line 21))
               ((file_name tests/ex08.ml) (line 21)))
              ((path_name ((path ()) (base xs))) (depth 0)))))))))))))))
 (Value
  (Known ((file_name tests/ex08.ml) (line 23))
   ((file_name tests/ex08.ml) (line 26)))
  ((is_rec (New true))
   (cases
    ((((name sum) (typ_vars ())
       (args
        ((l
          (Apply ((path_name ((path ()) (base t2))) (depth 0))
           ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))))
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Match
       (Known ((file_name tests/ex08.ml) (line 24))
        ((file_name tests/ex08.ml) (line 26)))
       (Variable
        (Known ((file_name tests/ex08.ml) (line 24))
         ((file_name tests/ex08.ml) (line 24)))
        ((path_name ((path ()) (base l))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base D1))) (depth 0)) ())
         (Constant
          (Known ((file_name tests/ex08.ml) (line 25))
           ((file_name tests/ex08.ml) (line 25)))
          (Int 0)))
        ((Constructor ((path_name ((path ()) (base D2))) (depth 0))
          ((Variable x) (Variable xs)))
         (Apply
          (Known ((file_name tests/ex08.ml) (line 26))
           ((file_name tests/ex08.ml) (line 26)))
          (Variable
           (Known ((file_name tests/ex08.ml) (line 26))
            ((file_name tests/ex08.ml) (line 26)))
           ((path_name ((path (Z)) (base add))) (depth 1)))
          ((Variable
            (Known ((file_name tests/ex08.ml) (line 26))
             ((file_name tests/ex08.ml) (line 26)))
            ((path_name ((path ()) (base x))) (depth 0)))
           (Apply
            (Known ((file_name tests/ex08.ml) (line 26))
             ((file_name tests/ex08.ml) (line 26)))
            (Variable
             (Known ((file_name tests/ex08.ml) (line 26))
              ((file_name tests/ex08.ml) (line 26)))
             ((path_name ((path ()) (base sum))) (depth 0)))
            ((Variable
              (Known ((file_name tests/ex08.ml) (line 26))
               ((file_name tests/ex08.ml) (line 26)))
              ((path_name ((path ()) (base xs))) (depth 0)))))))))))))))
 (Value
  (Known ((file_name tests/ex08.ml) (line 28))
   ((file_name tests/ex08.ml) (line 28)))
  ((is_rec (New false))
   (cases
    ((((name s) (typ_vars (A)) (args ((x (Variable A))))
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Match Unknown
       (Variable Unknown ((path_name ((path ()) (base x))) (depth 0)))
       ((Any
         (Apply
          (Known ((file_name tests/ex08.ml) (line 28))
           ((file_name tests/ex08.ml) (line 28)))
          (Variable
           (Known ((file_name tests/ex08.ml) (line 28))
            ((file_name tests/ex08.ml) (line 28)))
           ((path_name ((path ()) (base sum))) (depth 0)))
          ((Apply
            (Known ((file_name tests/ex08.ml) (line 28))
             ((file_name tests/ex08.ml) (line 28)))
            (Variable
             (Known ((file_name tests/ex08.ml) (line 28))
              ((file_name tests/ex08.ml) (line 28)))
             ((path_name ((path ()) (base of_list))) (depth 0)))
            ((Constructor
              (Known ((file_name tests/ex08.ml) (line 28))
               ((file_name tests/ex08.ml) (line 28)))
              ((path_name ((path ()) (base cons))) (depth 1))
              ((Constant
                (Known ((file_name tests/ex08.ml) (line 28))
                 ((file_name tests/ex08.ml) (line 28)))
                (Int 5))
               (Constructor
                (Known ((file_name tests/ex08.ml) (line 28))
                 ((file_name tests/ex08.ml) (line 28)))
                ((path_name ((path ()) (base cons))) (depth 1))
                ((Constant
                  (Known ((file_name tests/ex08.ml) (line 28))
                   ((file_name tests/ex08.ml) (line 28)))
                  (Int 7))
                 (Constructor
                  (Known ((file_name tests/ex08.ml) (line 28))
                   ((file_name tests/ex08.ml) (line 28)))
                  ((path_name ((path ()) (base cons))) (depth 1))
                  ((Constant
                    (Known ((file_name tests/ex08.ml) (line 28))
                     ((file_name tests/ex08.ml) (line 28)))
                    (Int 3))
                   (Constructor
                    (Known ((file_name tests/ex08.ml) (line 28))
                     ((file_name tests/ex08.ml) (line 28)))
                    ((path_name ((path ()) (base []))) (depth 1)) ())))))))))))))))))))
 (TypeDefinition
  (Known ((file_name tests/ex08.ml) (line 30))
   ((file_name tests/ex08.ml) (line 30)))
  (Abstract t3 ()))
 (TypeDefinition
  (Known ((file_name tests/ex08.ml) (line 31))
   ((file_name tests/ex08.ml) (line 31)))
  (Abstract t4 (a)))
 (TypeDefinition
  (Known ((file_name tests/ex08.ml) (line 32))
   ((file_name tests/ex08.ml) (line 32)))
  (Inductive t5 () ((C ())))))
