((),
  Value (non_rec, 'l', [ ], [ ], Some Type ('list', Type ('Z'))) =
    Let 4
      (rec, 'map_rec', [ 'A'; 'B' ],
        [
          ('counter', Type ('nat'));
          ('f', ('B' -> 'A'));
          ('match_var_0', Type ('list', 'B'))
        ], Some Type ('list', 'A')) =
      Match
        (?, Variable (?, 'counter'),
          [
            (Nat(0),
              Apply
                (?, Variable (?, 'not_terminated'),
                  Variable (?, 'tt')));
            (Constructor ('S', 'counter'),
              Match
                (?, Variable (?, 'match_var_0'),
                  [
                    (Constructor ('[]'),
                      Constructor
                        (5,
                          '[]'));
                    (Constructor
                      ('cons',
                        'x',
                        'xs'),
                      Constructor
                        (6,
                          'cons',
                          Apply
                            (6,
                              Variable
                                (6,
                                  'f'),
                              Variable
                                (6,
                                  'x')),
                          Apply
                            (?,
                              Apply
                                (6,
                                  Apply
                                    (?,
                                      Variable
                                        (?,
                                          'map_rec'),
                                      Variable
                                        (?,
                                          'counter')),
                                  Variable
                                    (6,
                                      'f')),
                              Variable
                                (6,
                                  'xs'))))
                  ]))
          ]) in
    Let 4
      (non_rec, 'map', [ 'A'; 'B' ],
        [ ('f', ('B' -> 'A')); ('match_var_0', Type ('list', 'B')) ],
        Some Type ('list', 'A')) =
      Let ? (non_rec, 'counter', [ ], [ ], None) =
        Apply (?, Variable (?, 'read_counter'), Variable (?, 'tt')) in
      Apply
        (?,
          Apply
            (?, Apply (?, Variable (?, 'map_rec'), Variable (?, 'counter')),
              Variable (?, 'f')), Variable (?, 'match_var_0')) in
    Let 7
      (rec, 'loop_rec', [ 'A' ], [ ('counter', Type ('nat')); ('x', 'A') ],
        Some 'A') =
      Match
        (?, Variable (?, 'counter'),
          [
            (Nat(0),
              Apply
                (?, Variable (?, 'not_terminated'),
                  Variable (?, 'tt')));
            (Constructor ('S', 'counter'), Variable (7, 'x'))
          ]) in
    Let 7 (non_rec, 'loop', [ 'A' ], [ ('x', 'A') ], Some 'A') =
      Let ? (non_rec, 'counter', [ ], [ ], None) =
        Apply (?, Variable (?, 'read_counter'), Variable (?, 'tt')) in
      Apply
        (?, Apply (?, Variable (?, 'loop_rec'), Variable (?, 'counter')),
          Variable (?, 'x')) in
    Apply
      (?,
        Apply
          (8, Variable (8, 'map'),
            Function
              (8, 'n',
                Apply
                  (?, Apply (8, Variable (8, 'Z.add'), Variable (8, 'n')),
                    Constant (8, Int(1))))),
        Constructor
          (8, 'cons', Constant (8, Int(5)),
            Constructor
              (8, 'cons', Constant (8, Int(7)),
                Constructor
                  (8, 'cons', Constant (8, Int(8)), Constructor (8, '[]'))))))
