Value 'l':
  (non_rec, [ ], [ ],
    (LetFun
      (rec, 'map', [ 'A'; 'B' ],
        Match
          ('match_var_0',
            [
              (Constructor ('[]'), Constructor ('[]'));
              (Constructor ('cons', 'x', 'xs'),
                Constructor
                  ('cons', Apply ('f', 'x'),
                    Apply ('map', 'f', 'xs')))
            ]),
        Apply
          ('map', Function ('n', Type ('Z'), Apply ('Z.add', 'n', Int(1))),
            Constructor
              ('cons', Int(5),
                Constructor
                  ('cons', Int(7),
                    Constructor ('cons', Int(8), Constructor ('[]')))))),
      Type ('list', Type ('Z'))))
