((Module (Known tests/ex10.ml ((line 3)) ((line 20))) List2
  ((TypeDefinition (Known tests/ex10.ml ((line 4)) ((line 6)))
    (Inductive t (a)
     ((Nil ())
      (Cons
       ((Variable a)
        (Apply ((path_name ((path ()) (base t))) (depth 0)) ((Variable a))))))))
   (Value (Known tests/ex10.ml ((line 8)) ((line 11)))
    ((is_rec (New true))
     (cases
      ((((name sum) (typ_vars ())
         (args
          ((l
            (Apply ((path_name ((path ()) (base t))) (depth 0))
             ((Apply ((path_name ((path ()) (base Z))) (depth 2)) ()))))))
         (typ ((Apply ((path_name ((path ()) (base Z))) (depth 2)) ()))))
        (Match (Variable ((path_name ((path ()) (base l))) (depth 0)))
         (((Constructor ((path_name ((path ()) (base Nil))) (depth 0)) ())
           (Constant (Int 0)))
          ((Constructor ((path_name ((path ()) (base Cons))) (depth 0))
            ((Variable x) (Variable xs)))
           (Apply (Variable ((path_name ((path (Z)) (base add))) (depth 2)))
            ((Variable ((path_name ((path ()) (base x))) (depth 0)))
             (Apply (Variable ((path_name ((path ()) (base sum))) (depth 0)))
              ((Variable ((path_name ((path ()) (base xs))) (depth 0)))))))))))))))
   (Value (Known tests/ex10.ml ((line 13)) ((line 15)))
    ((is_rec (New true))
     (cases
      ((((name of_list) (typ_vars (A))
         (args
          ((x
            (Apply ((path_name ((path ()) (base list))) (depth 2))
             ((Variable A))))))
         (typ
          ((Apply ((path_name ((path ()) (base t))) (depth 0))
            ((Variable A))))))
        (Match (Variable ((path_name ((path ()) (base x))) (depth 0)))
         (((Constructor ((path_name ((path ()) (base []))) (depth 2)) ())
           (Constructor ((path_name ((path ()) (base Nil))) (depth 0)) ()))
          ((Constructor ((path_name ((path ()) (base cons))) (depth 2))
            ((Variable x) (Variable xs)))
           (Constructor ((path_name ((path ()) (base Cons))) (depth 0))
            ((Variable ((path_name ((path ()) (base x))) (depth 0)))
             (Apply
              (Variable ((path_name ((path ()) (base of_list))) (depth 0)))
              ((Variable ((path_name ((path ()) (base xs))) (depth 0)))))))))))))))
   (Module (Known tests/ex10.ml ((line 17)) ((line 19))) Inside
    ((Value (Known tests/ex10.ml ((line 18)) ((line 18)))
      ((is_rec (New false))
       (cases
        ((((name x) (typ_vars ()) (args ())
           (typ ((Apply ((path_name ((path ()) (base Z))) (depth 3)) ()))))
          (Constant (Int 12)))))))))))
 (Value (Known tests/ex10.ml ((line 22)) ((line 22)))
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars (A)) (args ((x (Variable A))))
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Match (Variable ((path_name ((path ()) (base x))) (depth 0)))
       ((Any
         (Apply
          (Variable ((path_name ((path (List2)) (base sum))) (depth 0)))
          ((Apply
            (Variable
             ((path_name ((path (List2)) (base of_list))) (depth 0)))
            ((Constructor ((path_name ((path ()) (base cons))) (depth 1))
              ((Constant (Int 5))
               (Constructor ((path_name ((path ()) (base cons))) (depth 1))
                ((Constant (Int 7))
                 (Constructor ((path_name ((path ()) (base cons))) (depth 1))
                  ((Constant (Int 6))
                   (Constructor
                    ((path_name ((path ()) (base cons))) (depth 1))
                    ((Variable
                      ((path_name ((path (List2 Inside)) (base x)))
                       (depth 0)))
                     (Constructor
                      ((path_name ((path ()) (base []))) (depth 1)) ()))))))))))))))))))))))
