((Module (Known tests/ex11.ml ((line 3)) ((line 7))) SizedString
  ((TypeDefinition (Known tests/ex11.ml ((line 4)) ((line 6)))
    (Record t
     ((name (Apply ((path_name ((path ()) (base string))) (depth 2)) ()))
      (size (Apply ((path_name ((path ()) (base Z))) (depth 2)) ())))))))
 (Value (Known tests/ex11.ml ((line 9)) ((line 9)))
  ((is_rec (New false))
   (cases
    ((((name r) (typ_vars ()) (args ())
       (typ
        ((Apply ((path_name ((path (SizedString)) (base t))) (depth 0)) ()))))
      (Record
       ((((path_name ((path (SizedString)) (base name))) (depth 0))
         (Constant (String gre)))
        (((path_name ((path (SizedString)) (base size))) (depth 0))
         (Constant (Int 3))))))))))
 (Value (Known tests/ex11.ml ((line 10)) ((line 10)))
  ((is_rec (New false))
   (cases
    ((((name r') (typ_vars ()) (args ())
       (typ
        ((Apply ((path_name ((path (SizedString)) (base t))) (depth 0)) ()))))
      (Record
       ((((path_name ((path (SizedString)) (base name))) (depth 0))
         (Constant (String haha)))
        (((path_name ((path (SizedString)) (base size))) (depth 0))
         (Constant (Int 4))))))))))
 (Value (Known tests/ex11.ml ((line 12)) ((line 12)))
  ((is_rec (New false))
   (cases
    ((((name s) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path (Z)) (base add))) (depth 1)))
       ((Field (Variable ((path_name ((path ()) (base r))) (depth 0)))
         ((path_name ((path (SizedString)) (base size))) (depth 0)))
        (Field (Variable ((path_name ((path ()) (base r'))) (depth 0)))
         ((path_name ((path (SizedString)) (base size))) (depth 0))))))))))
 (Value (Known tests/ex11.ml ((line 14)) ((line 16)))
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars ())
       (args
        ((x
          (Apply ((path_name ((path (SizedString)) (base t))) (depth 0)) ()))))
       (typ ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))
      (Match (Variable ((path_name ((path ()) (base x))) (depth 0)))
       (((Record
          ((((path_name ((path (SizedString)) (base size))) (depth 0))
            (Constant (Int 3)))))
         (Constructor ((path_name ((path ()) (base true))) (depth 1)) ()))
        (Any
         (Constructor ((path_name ((path ()) (base false))) (depth 1)) ())))))))))
 (Value (Known tests/ex11.ml ((line 18)) ((line 18)))
  ((is_rec (New false))
   (cases
    ((((name b) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path ()) (base f))) (depth 0)))
       ((Variable ((path_name ((path ()) (base r))) (depth 0))))))))))
 (Value (Known tests/ex11.ml ((line 19)) ((line 19)))
  ((is_rec (New false))
   (cases
    ((((name b') (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path ()) (base f))) (depth 0)))
       ((Variable ((path_name ((path ()) (base r'))) (depth 0))))))))))
 (Module (Known tests/ex11.ml ((line 21)) ((line 32))) Point
  ((TypeDefinition (Known tests/ex11.ml ((line 22)) ((line 25)))
    (Record t
     ((x (Apply ((path_name ((path ()) (base Z))) (depth 2)) ()))
      (y (Apply ((path_name ((path ()) (base Z))) (depth 2)) ()))
      (z (Apply ((path_name ((path ()) (base Z))) (depth 2)) ())))))
   (Value (Known tests/ex11.ml ((line 27)) ((line 27)))
    ((is_rec (New false))
     (cases
      ((((name p) (typ_vars ()) (args ())
         (typ ((Apply ((path_name ((path ()) (base t))) (depth 0)) ()))))
        (Record
         ((((path_name ((path ()) (base x))) (depth 0)) (Constant (Int 5)))
          (((path_name ((path ()) (base y))) (depth 0)) (Constant (Int -3)))
          (((path_name ((path ()) (base z))) (depth 0)) (Constant (Int 1))))))))))
   (Value (Known tests/ex11.ml ((line 29)) ((line 31)))
    ((is_rec (New false))
     (cases
      ((((name b) (typ_vars ()) (args ())
         (typ ((Apply ((path_name ((path ()) (base bool))) (depth 2)) ()))))
        (Match (Variable ((path_name ((path ()) (base p))) (depth 0)))
         (((Record
            ((((path_name ((path ()) (base x))) (depth 0))
              (Constant (Int 5)))
             (((path_name ((path ()) (base z))) (depth 0))
              (Constant (Int 1)))))
           (Constructor ((path_name ((path ()) (base true))) (depth 2)) ()))
          (Any
           (Constructor ((path_name ((path ()) (base false))) (depth 2)) ()))))))))))))
