((Module SizedString
  ((TypeDefinition
    (Record t
     ((name (Apply ((path ()) (base string)) ()))
      (size (Apply ((path ()) (base Z)) ())))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name r) (typ_vars ()) (args ())
       (typ ((Apply ((path (SizedString)) (base t)) ()))))
      (Record
       ((((path (SizedString)) (base name)) (Constant (String gre)))
        (((path (SizedString)) (base size)) (Constant (Int 3))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name r') (typ_vars ()) (args ())
       (typ ((Apply ((path (SizedString)) (base t)) ()))))
      (Record
       ((((path (SizedString)) (base name)) (Constant (String haha)))
        (((path (SizedString)) (base size)) (Constant (Int 4))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name s) (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base Z)) ()))))
      (Apply (Variable ((path (Z)) (base add)))
       ((Field (Variable ((path ()) (base r)))
         ((path (SizedString)) (base size)))
        (Field (Variable ((path ()) (base r')))
         ((path (SizedString)) (base size))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars ())
       (args
        ((function_parameter (Apply ((path (SizedString)) (base t)) ()))))
       (typ ((Apply ((path ()) (base bool)) ()))))
      (Match (Variable ((path ()) (base function_parameter)))
       (((Record ((((path (SizedString)) (base size)) (Constant (Int 3)))))
         (Constructor ((path ()) (base true)) ()))
        (Any (Constructor ((path ()) (base false)) ())))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name b) (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base bool)) ()))))
      (Apply (Variable ((path ()) (base f)))
       ((Variable ((path ()) (base r))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name b') (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base bool)) ()))))
      (Apply (Variable ((path ()) (base f)))
       ((Variable ((path ()) (base r'))))))))))
 (Module Point
  ((TypeDefinition
    (Record t
     ((x (Apply ((path ()) (base Z)) ())) (y (Apply ((path ()) (base Z)) ()))
      (z (Apply ((path ()) (base Z)) ())))))
   (Value
    ((is_rec (New false))
     (cases
      ((((name p) (typ_vars ()) (args ())
         (typ ((Apply ((path ()) (base t)) ()))))
        (Record
         ((((path ()) (base x)) (Constant (Int 5)))
          (((path ()) (base y)) (Constant (Int -3)))
          (((path ()) (base z)) (Constant (Int 1))))))))))
   (Value
    ((is_rec (New false))
     (cases
      ((((name b) (typ_vars ()) (args ())
         (typ ((Apply ((path ()) (base bool)) ()))))
        (Match (Variable ((path ()) (base p)))
         (((Record
            ((((path ()) (base x)) (Constant (Int 5)))
             (((path ()) (base z)) (Constant (Int 1)))))
           (Constructor ((path ()) (base true)) ()))
          (Any (Constructor ((path ()) (base false)) ()))))))))))))
