Inductive tree:
  ([ ], [ (Leaf, [ ]); (Node, [ Type (tree/0); Type (Z/1); Type (tree/0) ]) ])

((),
  Value
    (rec, find, [ ], [ (x, Type (Z/1)); (t, Type (tree/0)) ], Some Type (bool/1))
    =
    Match
      (8, Variable (8, t/0),
        [
          (Constructor (Leaf/0), Constructor (9, false/1));
          (Constructor (Node/0, t1, x', t2),
            IfThenElse
              (11,
                Apply
                  (?,
                    Apply
                      (11,
                        Variable
                          (11,
                            Z.ltb/1),
                        Variable
                          (11,
                            x/0)),
                    Variable (11, x'/0)),
                Apply
                  (?,
                    Apply
                      (12,
                        Variable
                          (12,
                            find/0),
                        Variable
                          (12,
                            x/0)),
                    Variable (12, t1/0)),
                IfThenElse
                  (13,
                    Apply
                      (?,
                        Apply
                          (13,
                            Variable
                              (13,
                                Z.ltb/1),
                            Variable
                              (13,
                                x'/0)),
                        Variable
                          (13,
                            x/0)),
                    Apply
                      (?,
                        Apply
                          (14,
                            Variable
                              (14,
                                find/0),
                            Variable
                              (14,
                                x/0)),
                        Variable
                          (14,
                            t2/0)),
                    Constructor (16, true/1))))
        ]))
