((),
  Value
    (non_rec, 'tail', [ 'A' ], [ ('l', Type ('list', 'A')) ],
      Some Type ('list', 'A')) =
    Match
      (unknown, Variable (unknown, 'l'),
        [
          (Constructor ('cons', Any, 'xs'), Variable (unknown, 'xs'));
          (Constructor ('[]'),
            Apply
              (unknown, Variable (unknown, 'failwith'),
                Constant
                  (unknown,
                    String("Cannot take the tail of an empty list."))))
        ]))

((),
  Value
    (rec, 'print_list_rec', [ ],
      [
        ('counter', Type ('nat'));
        ('match_var_0', Type ('list', Type ('string')))
      ], Some Type ('unit')) =
    Match
      (unknown, Variable (unknown, 'counter'),
        [
          (Nat(0),
            Apply
              (unknown, Variable (unknown, 'not_terminated'),
                Variable (unknown, 'tt')));
          (Constructor ('S', 'counter'),
            Match
              (unknown, Variable (unknown, 'match_var_0'),
                [
                  (Constructor ('[]'),
                    Constructor
                      (unknown,
                        'tt'));
                  (Constructor ('cons', 'x', 'xs'),
                    Sequence
                      (unknown,
                        Apply
                          (unknown,
                            Variable
                              (unknown,
                                'print_string'),
                            Variable
                              (unknown,
                                'x')),
                        Apply
                          (unknown,
                            Apply
                              (unknown,
                                Variable
                                  (unknown,
                                    'print_list_rec'),
                                Variable
                                  (unknown,
                                    'counter')),
                            Variable
                              (unknown,
                                'xs'))))
                ]))
        ]))

((),
  Value
    (non_rec, 'print_list', [ ],
      [ ('match_var_0', Type ('list', Type ('string'))) ], Some Type ('unit')) =
    Let unknown (non_rec, 'counter', [ ], [ ], None) =
      Apply
        (unknown, Variable (unknown, 'read_counter'), Variable (unknown, 'tt'))
      in
    Apply
      (unknown,
        Apply
          (unknown, Variable (unknown, 'print_list_rec'),
            Variable (unknown, 'counter')), Variable (unknown, 'match_var_0')))

((),
  Value
    (non_rec, 'f', [ ], [ ],
      Some (Type ('list', Type ('string')) -> Type ('unit'))) =
    Variable (unknown, 'print_list'))

((),
  Value (non_rec, 'x', [ 'A' ], [ ('z', 'A') ], Some Type ('unit')) =
    Apply
      (unknown, Variable (unknown, 'f'),
        Apply
          (unknown, Variable (unknown, 'tail'),
            Constructor
              (unknown, 'cons', Constant (unknown, String("Stop")),
                Constructor
                  (unknown, 'cons', Constant (unknown, String("Hello")),
                    Constructor
                      (unknown, 'cons', Constant (unknown, String(" ")),
                        Constructor
                          (unknown, 'cons', Constant (unknown, String("world")),
                            Constructor (unknown, '[]'))))))))
