((),
  Value
    (non_rec, 'f', [ ], [ ('n', Type ('Z')); ('b', Type ('bool')) ],
      Some Type ('Z')) =
    IfThenElse
      (unknown, Variable (unknown, 'b'),
        Apply
          (unknown,
            Apply
              (unknown, Variable (unknown, 'Z.add'), Variable (unknown, 'n')),
            Constant (unknown, Int(1))),
        Apply
          (unknown,
            Apply
              (unknown, Variable (unknown, 'Z.sub'), Variable (unknown, 'n')),
            Constant (unknown, Int(1)))))
