((Value
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars ())
       (args
        ((n (Apply ((path ()) (base Z)) ()))
         (b (Apply ((path ()) (base bool)) ()))))
       (typ ((Apply ((path ()) (base Z)) ()))))
      (IfThenElse (Variable ((path ()) (base b)))
       (Apply (Variable ((path (Z)) (base add)))
        ((Variable ((path ()) (base n))) (Constant (Int 1))))
       (Apply (Variable ((path (Z)) (base sub)))
        ((Variable ((path ()) (base n))) (Constant (Int 1)))))))))))
