Inductive set:
  ([ ], [ (Empty, [ ]); (Node, [ Type (set/0); Type (Z/1); Type (set/0) ]) ])

((),
  Value (non_rec, empty, [ ], [ ], Some Type (set/0)) =
    Constructor (7, Empty/0))

((),
  Value
    (rec, member, [ ], [ (x, Type (Z/1)); (s, Type (set/0)) ],
      Some Type (bool/1)) =
    Match
      (10, Variable (10, s/0),
        [
          (Constructor (Empty/0), Constructor (11, false/1));
          (Constructor (Node/0, s1, y, s2),
            IfThenElse
              (13,
                Apply
                  (?,
                    Apply
                      (13,
                        Variable
                          (13,
                            Z.ltb/1),
                        Variable
                          (13,
                            x/0)),
                    Variable (13, y/0)),
                Apply
                  (?,
                    Apply
                      (14,
                        Variable
                          (14,
                            member/0),
                        Variable
                          (14,
                            x/0)),
                    Variable (14, s1/0)),
                IfThenElse
                  (15,
                    Apply
                      (?,
                        Apply
                          (15,
                            Variable
                              (15,
                                Z.ltb/1),
                            Variable
                              (15,
                                y/0)),
                        Variable
                          (15,
                            x/0)),
                    Apply
                      (?,
                        Apply
                          (16,
                            Variable
                              (16,
                                member/0),
                            Variable
                              (16,
                                x/0)),
                        Variable
                          (16,
                            s2/0)),
                    Constructor (18, true/1))))
        ]))

((),
  Value
    (rec, insert, [ ], [ (x, Type (Z/1)); (s, Type (set/0)) ], Some Type (set/0))
    =
    Match
      (21, Variable (21, s/0),
        [
          (Constructor (Empty/0),
            Constructor
              (22, Node/0, Constructor (22, Empty/0),
                Variable (22, x/0), Constructor (22, Empty/0)));
          (Constructor (Node/0, s1, y, s2),
            IfThenElse
              (24,
                Apply
                  (?,
                    Apply
                      (24,
                        Variable
                          (24,
                            Z.ltb/1),
                        Variable
                          (24,
                            x/0)),
                    Variable (24, y/0)),
                Constructor
                  (25, Node/0,
                    Apply
                      (?,
                        Apply
                          (25,
                            Variable
                              (25,
                                insert/0),
                            Variable
                              (25,
                                x/0)),
                        Variable
                          (25,
                            s1/0)),
                    Variable (25, y/0),
                    Variable (25, s2/0)),
                IfThenElse
                  (26,
                    Apply
                      (?,
                        Apply
                          (26,
                            Variable
                              (26,
                                Z.ltb/1),
                            Variable
                              (26,
                                y/0)),
                        Variable
                          (26,
                            x/0)),
                    Constructor
                      (27, Node/0,
                        Variable
                          (27,
                            s1/0),
                        Variable
                          (27,
                            y/0),
                        Apply
                          (?,
                            Apply
                              (27,
                                Variable
                                  (27,
                                    insert/0),
                                Variable
                                  (27,
                                    x/0)),
                            Variable
                              (27,
                                s2/0))),
                    Variable (28, s/0))))
        ]))
