Inductive 'set':
  ([ ], [ ('Empty', [ ]); ('Node', [ Type ('set'); Type ('Z'); Type ('set') ]) ])

((),
  Value (non_rec, 'empty', [ ], [ ], Some Type ('set')) =
    Constructor (unknown, 'Empty'))

((),
  Value
    (rec, 'member_rec', [ ],
      [ ('counter', Type ('nat')); ('x', Type ('Z')); ('s', Type ('set')) ],
      Some Type ('bool')) =
    Match
      (unknown, Variable (unknown, 'counter'),
        [
          (Nat(0),
            Apply
              (unknown, Variable (unknown, 'not_terminated'),
                Variable (unknown, 'tt')));
          (Constructor ('S', 'counter'),
            Match
              (unknown, Variable (unknown, 's'),
                [
                  (Constructor ('Empty'),
                    Constructor
                      (unknown,
                        'false'));
                  (Constructor ('Node', 's1', 'y', 's2'),
                    IfThenElse
                      (unknown,
                        Apply
                          (unknown,
                            Apply
                              (unknown,
                                Variable
                                  (unknown,
                                    'Z.ltb'),
                                Variable
                                  (unknown,
                                    'x')),
                            Variable
                              (unknown,
                                'y')),
                        Apply
                          (unknown,
                            Apply
                              (unknown,
                                Apply
                                  (unknown,
                                    Variable
                                      (unknown,
                                        'member_rec'),
                                    Variable
                                      (unknown,
                                        'counter')),
                                Variable
                                  (unknown,
                                    'x')),
                            Variable
                              (unknown,
                                's1')),
                        IfThenElse
                          (unknown,
                            Apply
                              (unknown,
                                Apply
                                  (unknown,
                                    Variable
                                      (unknown,
                                        'Z.ltb'),
                                    Variable
                                      (unknown,
                                        'y')),
                                Variable
                                  (unknown,
                                    'x')),
                            Apply
                              (unknown,
                                Apply
                                  (unknown,
                                    Apply
                                      (unknown,
                                        Variable
                                          (unknown,
                                            'member_rec'),
                                        Variable
                                          (unknown,
                                            'counter')),
                                    Variable
                                      (unknown,
                                        'x')),
                                Variable
                                  (unknown,
                                    's2')),
                            Constructor
                              (unknown,
                                'true'))))
                ]))
        ]))

((),
  Value
    (non_rec, 'member', [ ], [ ('x', Type ('Z')); ('s', Type ('set')) ],
      Some Type ('bool')) =
    Let unknown (non_rec, 'counter', [ ], [ ], None) =
      Apply
        (unknown, Variable (unknown, 'read_counter'), Variable (unknown, 'tt'))
      in
    Apply
      (unknown,
        Apply
          (unknown,
            Apply
              (unknown, Variable (unknown, 'member_rec'),
                Variable (unknown, 'counter')), Variable (unknown, 'x')),
        Variable (unknown, 's')))

((),
  Value
    (rec, 'insert_rec', [ ],
      [ ('counter', Type ('nat')); ('x', Type ('Z')); ('s', Type ('set')) ],
      Some Type ('set')) =
    Match
      (unknown, Variable (unknown, 'counter'),
        [
          (Nat(0),
            Apply
              (unknown, Variable (unknown, 'not_terminated'),
                Variable (unknown, 'tt')));
          (Constructor ('S', 'counter'),
            Match
              (unknown, Variable (unknown, 's'),
                [
                  (Constructor ('Empty'),
                    Constructor
                      (unknown,
                        'Node',
                        Constructor
                          (unknown,
                            'Empty'),
                        Variable
                          (unknown,
                            'x'),
                        Constructor
                          (unknown,
                            'Empty')));
                  (Constructor ('Node', 's1', 'y', 's2'),
                    IfThenElse
                      (unknown,
                        Apply
                          (unknown,
                            Apply
                              (unknown,
                                Variable
                                  (unknown,
                                    'Z.ltb'),
                                Variable
                                  (unknown,
                                    'x')),
                            Variable
                              (unknown,
                                'y')),
                        Constructor
                          (unknown,
                            'Node',
                            Apply
                              (unknown,
                                Apply
                                  (unknown,
                                    Apply
                                      (unknown,
                                        Variable
                                          (unknown,
                                            'insert_rec'),
                                        Variable
                                          (unknown,
                                            'counter')),
                                    Variable
                                      (unknown,
                                        'x')),
                                Variable
                                  (unknown,
                                    's1')),
                            Variable
                              (unknown,
                                'y'),
                            Variable
                              (unknown,
                                's2')),
                        IfThenElse
                          (unknown,
                            Apply
                              (unknown,
                                Apply
                                  (unknown,
                                    Variable
                                      (unknown,
                                        'Z.ltb'),
                                    Variable
                                      (unknown,
                                        'y')),
                                Variable
                                  (unknown,
                                    'x')),
                            Constructor
                              (unknown,
                                'Node',
                                Variable
                                  (unknown,
                                    's1'),
                                Variable
                                  (unknown,
                                    'y'),
                                Apply
                                  (unknown,
                                    Apply
                                      (unknown,
                                        Apply
                                          (unknown,
                                            Variable
                                              (unknown,
                                                'insert_rec'),
                                            Variable
                                              (unknown,
                                                'counter')),
                                        Variable
                                          (unknown,
                                            'x')),
                                    Variable
                                      (unknown,
                                        's2'))),
                            Variable
                              (unknown,
                                's'))))
                ]))
        ]))

((),
  Value
    (non_rec, 'insert', [ ], [ ('x', Type ('Z')); ('s', Type ('set')) ],
      Some Type ('set')) =
    Let unknown (non_rec, 'counter', [ ], [ ], None) =
      Apply
        (unknown, Variable (unknown, 'read_counter'), Variable (unknown, 'tt'))
      in
    Apply
      (unknown,
        Apply
          (unknown,
            Apply
              (unknown, Variable (unknown, 'insert_rec'),
                Variable (unknown, 'counter')), Variable (unknown, 'x')),
        Variable (unknown, 's')))
