Exception ('TailLess', ())

Exception ('Wtf', (Type ('Z/1') * Type ('string/1')))

((),
  Value (non_rec, 'f', [ 'A'; 'B' ], [ ('x', 'B') ], Some 'A') =
    Apply (7, Variable (7, 'raise_TailLess/0'), Tuple (?)))

Module 'G':
  ((),
    Value (non_rec, 'g', [ 'A' ], [ ('x', Type ('Z/2')) ], Some 'A') =
      Apply
        (10, Variable (10, 'raise_Wtf/0'),
          Tuple (?, Variable (10, 'x/0'), Constant (10, String("no")))))

((),
  Value
    (rec, 'h_rec', [ 'A' ],
      [ ('counter', Type ('nat/0')); ('l', Type ('list/1', 'A')) ], Some 'A') =
    Match
      (?, Variable (?, 'counter/0'),
        [
          (Nat(0),
            Apply
              (?, Variable (?, 'not_terminated/0'),
                Variable (?, 'tt/0')));
          (Constructor ('S/0', 'counter'),
            Match
              (14, Variable (14, 'l/0'),
                [
                  (Constructor ('[]/0'),
                    Sequence
                      (15,
                        Apply
                          (15,
                            Variable
                              (15,
                                'print_string/0'),
                            Constant
                              (15,
                                String("no tail"))),
                        Apply
                          (15,
                            Variable
                              (15,
                                'raise_TailLess/0'),
                            Tuple
                              (?))));
                  (Constructor
                    ('cons/0',
                      'x',
                      Constructor
                        ('[]/0')),
                    Variable
                      (16,
                        'x/0'));
                  (Constructor ('cons/0', Any, 'xs'),
                    Apply
                      (17,
                        Apply
                          (?,
                            Variable
                              (?,
                                'h_rec/0'),
                            Variable
                              (?,
                                'counter/0')),
                        Variable
                          (17,
                            'xs/0')))
                ]))
        ]))

((),
  Value (non_rec, 'h', [ 'A' ], [ ('l', Type ('list/1', 'A')) ], Some 'A') =
    Let ? (non_rec, 'counter', [ ], [ ], None) =
      Apply (?, Variable (?, 'read_counter/0'), Variable (?, 'tt/0')) in
    Apply
      (?, Apply (?, Variable (?, 'h_rec/0'), Variable (?, 'counter/0')),
        Variable (?, 'l/0')))
