1 Reference (r, Type (Z/1))

3
((),
  Value (non_rec, plus_one, [ A ], [ (x, A) ], Some Type (Z/1)) =
    Match
      (?, Variable (?, x/0),
        [
          (Any,
            Apply
              (?,
                Apply
                  (4, Variable (4, Z.add/1),
                    Apply
                      (4,
                        Variable
                          (?,
                            read_r/0),
                        Tuple (?))),
                Constant (4, Int(1))))
        ]))

6 Reference (s, Type (string/1))

8
((),
  Value (non_rec, fail, [ A; B ], [ (x, B) ], Some A) =
    Match
      (?, Variable (?, x/0),
        [
          (Any,
            Apply
              (8, Variable (8, failwith/1),
                Apply (8, Variable (?, read_s/0), Tuple (?))))
        ]))
