3 Exception (Error, ())

5
(Value
  (non_rec, @.,
    [
      ((x1, [ ], [ ], Some Type (Z/0)),
        Match
          (6,
            Run
              (?, Error/0, [ ],
                Apply (6, Variable (6, raise_Error/0), [ Tuple (?) ])),
            [
              (Constructor (inl/0, x), Variable (?, x/0));
              (Constructor (inr/0, Tuple ()), Constant (7, Int(12)))
            ]))
    ]))

9
(Value
  (non_rec, @.,
    [
      ((x2, [ A; B ], [ (x, A) ], Some B),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Match
                  (10,
                    Run
                      (?,
                        Error/0,
                        [
                        ],
                        Apply
                          (10,
                            Variable
                              (10,
                                raise_Error/0),
                            [
                              Tuple
                                (?)
                            ])),
                    [
                      (Constructor
                        (inl/0,
                          x),
                        Variable
                          (?,
                            x/0));
                      (Constructor
                        (inr/0,
                          Tuple
                            ()),
                        Apply
                          (11,
                            Variable
                              (11,
                                OCaml.Pervasives.failwith/0),
                            [
                              Constant
                                (11,
                                  String("arg"))
                            ]))
                    ]))
            ]))
    ]))

13
(Value
  (non_rec, @.,
    [
      ((x3, [ ], [ (b, Type (bool/0)) ], Some Type (Z/0)),
        Match
          (14,
            Run
              (?, Error/0, [ ],
                IfThenElse
                  (14, Variable (14, b/0),
                    Apply
                      (14,
                        Variable
                          (14, OCaml.Pervasives.failwith/0),
                        [ Constant (14, String("arg")) ]),
                    Apply
                      (14, Variable (14, raise_Error/0),
                        [ Tuple (?) ]))),
            [
              (Constructor (inl/0, x), Variable (?, x/0));
              (Constructor (inr/0, Tuple ()), Constant (15, Int(12)))
            ]))
    ]))
