3
((),
  Value (non_rec, f, [ A; B; C ], [ (x, A) ], Some (C -> B)) =
    Sequence
      (4,
        Apply
          (4, Variable (4, OCaml.Pervasives.print_string/1),
            [ Constant (4, String("Hi")) ]),
        Function
          (5, y,
            Apply
              (5, Variable (5, OCaml.Pervasives.failwith/1),
                [ Constant (5, String("Bye")) ]))))

7
((),
  Value (non_rec, r, [ A; B ], [ (x, B) ], Some A) =
    Match
      (?, Variable (?, x/0),
        [
          (Any,
            Apply
              (7, Variable (7, f/0),
                [ Constant (7, Int(1)); Constant (7, Int(2)) ]))
        ]))
