((Value
  ((is_rec (New false))
   (cases
    ((((name op_plus_plus_plus) (typ_vars ())
       (args
        ((x (Apply ((path ()) (base Z)) ()))
         (y (Apply ((path ()) (base Z)) ()))))
       (typ ((Apply ((path ()) (base Z)) ()))))
      (Apply (Variable ((path (Z)) (base add)))
       ((Variable ((path ()) (base x))) (Variable ((path ()) (base y))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name op_tilde_tilde) (typ_vars ())
       (args ((x (Apply ((path ()) (base Z)) ()))))
       (typ ((Apply ((path ()) (base Z)) ()))))
      (Apply (Variable ((path (Z)) (base opp)))
       ((Variable ((path ()) (base x))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name z) (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base Z)) ()))))
      (Apply (Variable ((path ()) (base op_plus_plus_plus)))
       ((Apply (Variable ((path ()) (base op_tilde_tilde)))
         ((Constant (Int 12))))
        (Constant (Int 14))))))))))
