((Value
  ((is_rec (New false))
   (cases
    ((((name op_plus_plus_plus) (typ_vars ())
       (args
        ((x (Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))
         (y (Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path (Z)) (base add))) (depth 1)))
       ((Variable ((path_name ((path ()) (base x))) (depth 0)))
        (Variable ((path_name ((path ()) (base y))) (depth 0))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name op_tilde_tilde) (typ_vars ())
       (args ((x (Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path (Z)) (base opp))) (depth 1)))
       ((Variable ((path_name ((path ()) (base x))) (depth 0))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name z) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Apply
       (Variable
        ((path_name ((path ()) (base op_plus_plus_plus))) (depth 0)))
       ((Apply
         (Variable ((path_name ((path ()) (base op_tilde_tilde))) (depth 0)))
         ((Constant (Int 12))))
        (Constant (Int 14))))))))))
