3
Value
  (non_rec, @.,
    [ ((l1, [ ], [ ], Some Type (list/1, Type (Z/1))), Constructor (3, []/1)) ])

4
Value
  (non_rec, @.,
    [
      ((l2, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Constructor
          (4, cons/1, Constant (4, Int(1)),
            Constructor
              (4, cons/1, Constant (4, Int(2)),
                Constructor
                  (4, cons/1, Constant (4, Int(3)),
                    Constructor
                      (4, cons/1, Constant (4, Int(4)),
                        Constructor (4, []/1))))))
    ])

5
Value
  (non_rec, @.,
    [
      ((l3, [ ], [ ], Some Type (list/1, (Type (Z/1) * Type (string/1)))),
        Constructor
          (5, cons/1,
            Tuple (5, Constant (5, Int(1)), Constant (5, String("one"))),
            Constructor
              (5, cons/1,
                Tuple
                  (5, Constant (5, Int(2)),
                    Constant (5, String("two"))),
                Constructor (5, []/1))))
    ])

7
Value
  (non_rec, @.,
    [
      ((s1, [ ], [ ], Some Type (Z/1)),
        Apply (7, Variable (7, OCaml.List.length/1), [ Variable (7, l1/0) ]))
    ])

8
Value
  (non_rec, @.,
    [
      ((s2, [ ], [ ], Some Type (Z/1)),
        Apply (8, Variable (8, OCaml.List.length/1), [ Variable (8, l2/0) ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((h, [ A ], [ (x, A) ], Some Type (Z/1)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (9,
                    Variable
                      (9,
                        OCaml.List.hd/1),
                    [
                      Variable
                        (9,
                          l2/0)
                    ]))
            ]))
    ])

10
Value
  (non_rec, @.,
    [
      ((t, [ A ], [ (x, A) ], Some Type (list/1, Type (Z/1))),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (10,
                    Variable
                      (10,
                        OCaml.List.tl/1),
                    [
                      Variable
                        (10,
                          l2/0)
                    ]))
            ]))
    ])

11
Value
  (non_rec, @.,
    [
      ((x, [ A ], [ (x, A) ], Some Type (Z/1)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                Apply
                  (11,
                    Variable
                      (11,
                        OCaml.List.nth/1),
                    [
                      Variable
                        (11,
                          l2/0);
                      Constant
                        (11,
                          Int(1))
                    ]))
            ]))
    ])

12
Value
  (non_rec, @.,
    [
      ((rl, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply (12, Variable (12, OCaml.List.rev/1), [ Variable (12, l2/0) ]))
    ])

13
Value
  (non_rec, @.,
    [
      ((ll, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (13, Variable (13, OCaml.List.append/1),
            [ Variable (13, l2/0); Variable (13, l2/0) ]))
    ])

14
Value
  (non_rec, @.,
    [
      ((rll, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (14, Variable (14, OCaml.List.rev_append/1),
            [ Variable (14, l2/0); Variable (14, l2/0) ]))
    ])

15
Value
  (non_rec, @.,
    [
      ((lc, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (15, Variable (15, OCaml.List.concat/1),
            [
              Constructor
                (15, cons/1, Variable (15, l1/0),
                  Constructor
                    (15,
                      cons/1,
                      Variable
                        (15,
                          l2/0),
                      Constructor
                        (15,
                          cons/1,
                          Variable
                            (15,
                              l1/0),
                          Constructor
                            (15,
                              cons/1,
                              Variable
                                (15,
                                  l2/0),
                              Constructor
                                (15,
                                  []/1)))))
            ]))
    ])

16
Value
  (non_rec, @.,
    [
      ((lf, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (16, Variable (16, OCaml.List.flatten/1),
            [
              Constructor
                (16, cons/1, Variable (16, l1/0),
                  Constructor
                    (16,
                      cons/1,
                      Variable
                        (16,
                          l2/0),
                      Constructor
                        (16,
                          cons/1,
                          Variable
                            (16,
                              l1/0),
                          Constructor
                            (16,
                              cons/1,
                              Variable
                                (16,
                                  l2/0),
                              Constructor
                                (16,
                                  []/1)))))
            ]))
    ])

19
Value
  (non_rec, @.,
    [
      ((m, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (19, Variable (19, OCaml.List.map/1),
            [
              Function
                (19, x,
                  Apply
                    (19,
                      Variable
                        (19,
                          Z.add/1),
                      [
                        Variable
                          (19,
                            x/0);
                        Constant
                          (19,
                            Int(1))
                      ]));
              Variable (19, l2/0)
            ]))
    ])

20
Value
  (non_rec, @.,
    [
      ((mi, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (20, Variable (20, OCaml.List.mapi/1),
            [
              Function
                (20, i,
                  Function
                    (20,
                      x,
                      Apply
                        (20,
                          Variable
                            (20,
                              Z.add/1),
                          [
                            Variable
                              (20,
                                x/0);
                            Variable
                              (20,
                                i/0)
                          ])));
              Variable (20, l2/0)
            ]))
    ])

21
Value
  (non_rec, @.,
    [
      ((rm, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (21, Variable (21, OCaml.List.rev_map/1),
            [
              Function
                (21, x,
                  Apply
                    (21,
                      Variable
                        (21,
                          Z.add/1),
                      [
                        Variable
                          (21,
                            x/0);
                        Constant
                          (21,
                            Int(1))
                      ]));
              Variable (21, l2/0)
            ]))
    ])

22
Value
  (non_rec, @.,
    [
      ((fl, [ ], [ ], Some Type (Z/1)),
        Apply
          (22, Variable (22, OCaml.List.fold_left/1),
            [
              Function
                (22, s,
                  Function
                    (22,
                      x,
                      Apply
                        (22,
                          Variable
                            (22,
                              Z.add/1),
                          [
                            Variable
                              (22,
                                s/0);
                            Variable
                              (22,
                                x/0)
                          ])));
              Constant (22, Int(0));
              Variable (22, l2/0)
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((fr, [ ], [ ], Some Type (Z/1)),
        Apply
          (23, Variable (23, OCaml.List.fold_right/1),
            [
              Function
                (23, x,
                  Function
                    (23,
                      s,
                      Apply
                        (23,
                          Variable
                            (23,
                              Z.add/1),
                          [
                            Variable
                              (23,
                                s/0);
                            Variable
                              (23,
                                x/0)
                          ])));
              Variable (23, l2/0);
              Constant (23, Int(0))
            ]))
    ])

26
Value
  (non_rec, @.,
    [
      ((all, [ ], [ ], Some Type (bool/1)),
        Apply
          (26, Variable (26, OCaml.List.for_all/1),
            [
              Function
                (26, x,
                  Apply
                    (26,
                      Variable
                        (26,
                          equiv_decb/1),
                      [
                        Variable
                          (26,
                            x/0);
                        Constant
                          (26,
                            Int(2))
                      ]));
              Variable (26, l2/0)
            ]))
    ])

27
Value
  (non_rec, @.,
    [
      ((ex, [ ], [ ], Some Type (bool/1)),
        Apply
          (27, Variable (27, OCaml.List._exists/1),
            [
              Function
                (27, x,
                  Apply
                    (27,
                      Variable
                        (27,
                          equiv_decb/1),
                      [
                        Variable
                          (27,
                            x/0);
                        Constant
                          (27,
                            Int(2))
                      ]));
              Variable (27, l2/0)
            ]))
    ])

30
Value
  (non_rec, @.,
    [
      ((fin, [ A ], [ (x_1, A) ], Some Type (Z/1)),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (30,
                    Variable
                      (30,
                        OCaml.List.find/1),
                    [
                      Function
                        (30,
                          x,
                          Apply
                            (30,
                              Variable
                                (30,
                                  equiv_decb/1),
                              [
                                Variable
                                  (30,
                                    x/0);
                                Constant
                                  (30,
                                    Int(1))
                              ]));
                      Variable
                        (30,
                          l2/0)
                    ]))
            ]))
    ])

31
Value
  (non_rec, @.,
    [
      ((fil, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (31, Variable (31, OCaml.List.filter/1),
            [
              Function
                (31, x,
                  Apply
                    (31,
                      Variable
                        (31,
                          OCaml.Pervasives.ge/1),
                      [
                        Variable
                          (31,
                            x/0);
                        Constant
                          (31,
                            Int(2))
                      ]));
              Variable (31, l2/0)
            ]))
    ])

32
Value
  (non_rec, @.,
    [
      ((fina, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (32, Variable (32, OCaml.List.find_all/1),
            [
              Function
                (32, x,
                  Apply
                    (32,
                      Variable
                        (32,
                          OCaml.Pervasives.ge/1),
                      [
                        Variable
                          (32,
                            x/0);
                        Constant
                          (32,
                            Int(2))
                      ]));
              Variable (32, l2/0)
            ]))
    ])

33
Value
  (non_rec, @.,
    [
      ((par, [ ], [ ],
        Some (Type (list/1, Type (Z/1)) * Type (list/1, Type (Z/1)))),
        Apply
          (33, Variable (33, OCaml.List.partition/1),
            [
              Function
                (33, x,
                  Apply
                    (33,
                      Variable
                        (33,
                          OCaml.Pervasives.gt/1),
                      [
                        Variable
                          (33,
                            x/0);
                        Constant
                          (33,
                            Int(2))
                      ]));
              Variable (33, l2/0)
            ]))
    ])

36
Value
  (non_rec, @.,
    [
      ((asso, [ A ], [ (x_1, A) ], Some Type (string/1)),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (36,
                    Variable
                      (36,
                        OCaml.List.assoc/1),
                    [
                      Constant
                        (36,
                          Int(2));
                      Variable
                        (36,
                          l3/0)
                    ]))
            ]))
    ])

37
Value
  (non_rec, @.,
    [
      ((masso, [ A ], [ (x_1, A) ], Some Type (bool/1)),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (37,
                    Variable
                      (37,
                        OCaml.List.mem_assoc/1),
                    [
                      Constant
                        (37,
                          Int(2));
                      Variable
                        (37,
                          l3/0)
                    ]))
            ]))
    ])

38
Value
  (non_rec, @.,
    [
      ((rasso, [ A ], [ (x_1, A) ],
        Some Type (list/1, (Type (Z/1) * Type (string/1)))),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (38,
                    Variable
                      (38,
                        OCaml.List.remove_assoc/1),
                    [
                      Constant
                        (38,
                          Int(2));
                      Variable
                        (38,
                          l3/0)
                    ]))
            ]))
    ])

41
Value
  (non_rec, @.,
    [
      ((sp, [ ], [ ],
        Some (Type (list/1, Type (Z/1)) * Type (list/1, Type (string/1)))),
        Apply (41, Variable (41, OCaml.List.split/1), [ Variable (41, l3/0) ]))
    ])

42
Value
  (non_rec, @.,
    [
      ((com, [ A ], [ (x_1, A) ], Some Type (list/1, (Type (Z/1) * Type (Z/1)))),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (42,
                    Variable
                      (42,
                        OCaml.List.combine/1),
                    [
                      Variable
                        (42,
                          l2/0);
                      Variable
                        (42,
                          l2/0)
                    ]))
            ]))
    ])

45
Value
  (non_rec, @.,
    [
      ((so, [ A ], [ (x_1, A) ], Some Type (list/1, Type (Z/1))),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (45,
                    Variable
                      (45,
                        OCaml.List.sort/1),
                    [
                      Function
                        (45,
                          x,
                          Function
                            (45,
                              y,
                              Apply
                                (45,
                                  Variable
                                    (45,
                                      Z.sub/1),
                                  [
                                    Variable
                                      (45,
                                        y/0);
                                    Variable
                                      (45,
                                        x/0)
                                  ])));
                      Variable
                        (45,
                          l2/0)
                    ]))
            ]))
    ])

46
Value
  (non_rec, @.,
    [
      ((sso, [ A ], [ (x_1, A) ], Some Type (list/1, Type (Z/1))),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (46,
                    Variable
                      (46,
                        OCaml.List.stable_sort/1),
                    [
                      Function
                        (46,
                          x,
                          Function
                            (46,
                              y,
                              Apply
                                (46,
                                  Variable
                                    (46,
                                      Z.sub/1),
                                  [
                                    Variable
                                      (46,
                                        y/0);
                                    Variable
                                      (46,
                                        x/0)
                                  ])));
                      Variable
                        (46,
                          l2/0)
                    ]))
            ]))
    ])

47
Value
  (non_rec, @.,
    [
      ((fso, [ A ], [ (x_1, A) ], Some Type (list/1, Type (Z/1))),
        Match
          (?, Variable (?, x_1/0),
            [
              (Any,
                Apply
                  (47,
                    Variable
                      (47,
                        OCaml.List.fast_sort/1),
                    [
                      Function
                        (47,
                          x,
                          Function
                            (47,
                              y,
                              Apply
                                (47,
                                  Variable
                                    (47,
                                      Z.sub/1),
                                  [
                                    Variable
                                      (47,
                                        y/0);
                                    Variable
                                      (47,
                                        x/0)
                                  ])));
                      Variable
                        (47,
                          l2/0)
                    ]))
            ]))
    ])

48
Value
  (non_rec, @.,
    [
      ((mer, [ ], [ ], Some Type (list/1, Type (Z/1))),
        Apply
          (48, Variable (48, OCaml.List.merge/1),
            [
              Function
                (48, x,
                  Function
                    (48,
                      y,
                      Apply
                        (48,
                          Variable
                            (48,
                              Z.sub/1),
                          [
                            Variable
                              (48,
                                y/0);
                            Variable
                              (48,
                                x/0)
                          ])));
              Variable (48, l2/0);
              Constructor
                (48, cons/1, Constant (48, Int(2)),
                  Constructor
                    (48,
                      cons/1,
                      Constant
                        (48,
                          Int(-1)),
                      Constructor
                        (48,
                          cons/1,
                          Constant
                            (48,
                              Int(5)),
                          Constructor
                            (48,
                              []/1))))
            ]))
    ])
