3
Value
  (rec, @.,
    [
      ((f_map, [ A; B ], [ (f, (A -> B)); (l, Type (list/1, A)) ],
        Some Type (list/1, B)),
        Match
          (4, Variable (4, l/0),
            [
              (Constructor ([]/1), Constructor (5, []/1));
              (Constructor (cons/1, x, l),
                Constructor
                  (6, cons/1,
                    Apply
                      (6,
                        Variable
                          (6,
                            f/0),
                        [
                          Variable
                            (6,
                              x/0)
                        ]),
                    Apply
                      (6,
                        Variable
                          (6,
                            f_map/0),
                        [
                          Variable
                            (6,
                              f/0);
                          Variable
                            (6,
                              l/0)
                        ])))
            ]))
    ])

8
Value
  (non_rec, @.,
    [
      ((n, [ ], [ ], Some Type (Z/1)),
        LetFun 9
          (rec, @.,
            [
              ((sum, [ ], [ (l, Type (list/1, Type (Z/1))) ],
                Some Type (Z/1)),
                Match
                  (10,
                    Variable
                      (10,
                        l/0),
                    [
                      (Constructor
                        ([]/1),
                        Constant
                          (11,
                            Int(0)));
                      (Constructor
                        (cons/1,
                          x,
                          l),
                        Apply
                          (12,
                            Variable
                              (12,
                                Z.add/1),
                            [
                              Variable
                                (12,
                                  x/0);
                              Apply
                                (12,
                                  Variable
                                    (12,
                                      sum/0),
                                  [
                                    Variable
                                      (12,
                                        l/0)
                                  ])
                            ]))
                    ]))
            ]) in
        Apply
          (13, Variable (13, sum/0),
            [
              Constructor
                (13, cons/1, Constant (13, Int(1)),
                  Constructor
                    (13,
                      cons/1,
                      Constant
                        (13,
                          Int(2)),
                      Constructor
                        (13,
                          cons/1,
                          Constant
                            (13,
                              Int(3)),
                          Constructor
                            (13,
                              []/1))))
            ]))
    ])
