3
Value
  (rec, @coq_rec,
    [
      ((f_map, [ A; B ], [ (f, (A -> B)); (l, Type (list/1, A)) ],
        Some Type (list/1, B)),
        Match
          (4, Variable (4, l/0),
            [
              (Constructor ([]/1), Constructor (5, []/1));
              (Constructor (cons/1, x, l),
                Constructor
                  (6, cons/1,
                    Apply
                      (6,
                        Variable
                          (6,
                            f/0),
                        [
                          Variable
                            (6,
                              x/0)
                        ]),
                    Apply
                      (6,
                        Variable
                          (6,
                            f_map/0),
                        [
                          Variable
                            (6,
                              f/0);
                          Variable
                            (6,
                              l/0)
                        ])))
            ]))
    ])

9
Value
  (rec, @free_rec,
    [
      ((f_map2_rec, [ A; B ],
        [ (counter, Type (nat/1)); (f, (A -> B)); (l, Type (list/1, A)) ],
        Some Type (list/1, B)),
        Match
          (?, Variable (?, counter/0),
            [
              (Constructor (O/1),
                Apply
                  (?,
                    Variable
                      (?,
                        not_terminated/1),
                    [
                      Tuple
                        (?)
                    ]));
              (Constructor (S/1, counter),
                Match
                  (10,
                    Variable
                      (10,
                        l/0),
                    [
                      (Constructor
                        ([]/1),
                        Constructor
                          (11,
                            []/1));
                      (Constructor
                        (cons/1,
                          x,
                          l),
                        Constructor
                          (12,
                            cons/1,
                            Apply
                              (12,
                                Variable
                                  (12,
                                    f/0),
                                [
                                  Variable
                                    (12,
                                      x/0)
                                ]),
                            Apply
                              (12,
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        f_map2_rec/0),
                                    [
                                      Variable
                                        (?,
                                          counter/0)
                                    ]),
                                [
                                  Variable
                                    (12,
                                      f/0);
                                  Variable
                                    (12,
                                      l/0)
                                ])))
                    ]))
            ]))
    ])

9
Value
  (non_rec, @.,
    [
      ((f_map2, [ A; B ], [ (f, (A -> B)); (l, Type (list/1, A)) ],
        Some Type (list/1, B)),
        Apply
          (?, Variable (?, f_map2_rec/0),
            [
              Apply (?, Variable (?, read_counter/1), [ Tuple (?) ]);
              Variable (?, f/0);
              Variable (?, l/0)
            ]))
    ])

15
Value
  (non_rec, @.,
    [
      ((n, [ ], [ ], Some Type (Z/1)),
        LetFun 16
          (rec, @coq_rec,
            [
              ((sum, [ ], [ (l, Type (list/1, Type (Z/1))) ],
                Some Type (Z/1)),
                Match
                  (17,
                    Variable
                      (17,
                        l/0),
                    [
                      (Constructor
                        ([]/1),
                        Constant
                          (18,
                            Int(0)));
                      (Constructor
                        (cons/1,
                          x,
                          l),
                        Apply
                          (19,
                            Variable
                              (19,
                                Z.add/1),
                            [
                              Variable
                                (19,
                                  x/0);
                              Apply
                                (19,
                                  Variable
                                    (19,
                                      sum/0),
                                  [
                                    Variable
                                      (19,
                                        l/0)
                                  ])
                            ]))
                    ]))
            ]) in
        Apply
          (21, Variable (21, sum/0),
            [
              Constructor
                (21, cons/1, Constant (21, Int(1)),
                  Constructor
                    (21,
                      cons/1,
                      Constant
                        (21,
                          Int(2)),
                      Constructor
                        (21,
                          cons/1,
                          Constant
                            (21,
                              Int(3)),
                          Constructor
                            (21,
                              []/1))))
            ]))
    ])

23
Value
  (non_rec, @.,
    [
      ((n2, [ A ], [ (x, A) ], Some Type (Z/1)),
        Match
          (?, Variable (?, x/0),
            [
              (Any,
                LetFun 24
                  (rec, @free_rec,
                    [
                      ((sum_rec,
                        [
                        ],
                        [
                          (counter,
                            Type
                              (nat/1));
                          (l,
                            Type
                              (list/1,
                                Type
                                  (Z/1)))
                        ],
                        Some
                          Type
                            (Z/1)),
                        Match
                          (?,
                            Variable
                              (?,
                                counter/0),
                            [
                              (Constructor
                                (O/1),
                                Apply
                                  (?,
                                    Variable
                                      (?,
                                        not_terminated/1),
                                    [
                                      Tuple
                                        (?)
                                    ]));
                              (Constructor
                                (S/1,
                                  counter),
                                Match
                                  (25,
                                    Variable
                                      (25,
                                        l/0),
                                    [
                                      (Constructor
                                        ([]/1),
                                        Constant
                                          (26,
                                            Int(0)));
                                      (Constructor
                                        (cons/1,
                                          x,
                                          l),
                                        Apply
                                          (27,
                                            Variable
                                              (27,
                                                Z.add/1),
                                            [
                                              Variable
                                                (27,
                                                  x/0);
                                              Apply
                                                (27,
                                                  Apply
                                                    (?,
                                                      Variable
                                                        (?,
                                                          sum_rec/0),
                                                      [
                                                        Variable
                                                          (?,
                                                            counter/0)
                                                      ]),
                                                  [
                                                    Variable
                                                      (27,
                                                        l/0)
                                                  ])
                                            ]))
                                    ]))
                            ]))
                    ])
                  in
                LetFun 24
                  (non_rec, @.,
                    [
                      ((sum,
                        [
                        ],
                        [
                          (l,
                            Type
                              (list/1,
                                Type
                                  (Z/1)))
                        ],
                        Some
                          Type
                            (Z/1)),
                        Apply
                          (?,
                            Variable
                              (?,
                                sum_rec/0),
                            [
                              Apply
                                (?,
                                  Variable
                                    (?,
                                      read_counter/1),
                                  [
                                    Tuple
                                      (?)
                                  ]);
                              Variable
                                (?,
                                  l/0)
                            ]))
                    ])
                  in
                Apply
                  (29,
                    Variable
                      (29,
                        sum/0),
                    [
                      Constructor
                        (29,
                          cons/1,
                          Constant
                            (29,
                              Int(1)),
                          Constructor
                            (29,
                              cons/1,
                              Constant
                                (29,
                                  Int(2)),
                              Constructor
                                (29,
                                  cons/1,
                                  Constant
                                    (29,
                                      Int(3)),
                                  Constructor
                                    (29,
                                      []/1))))
                    ]))
            ]))
    ])
