3
Value
  (non_rec, @.,
    [
      ((map, [ A; B ], [ (f, (A -> B)); (l, Type (list/1, A)) ],
        Some Type (list/1, B)),
        LetFun 4
          (rec, @coq_rec,
            [
              ((map_coq_rec, [ ], [ (l, Type (list/1, A)) ],
                Some Type (list/1, B)),
                Match
                  (5, Variable (5, l/0),
                    [
                      (Constructor
                        ([]/1),
                        Constructor
                          (6,
                            []/1));
                      (Constructor
                        (cons/1,
                          x,
                          l),
                        Constructor
                          (7,
                            cons/1,
                            Apply
                              (7,
                                Variable
                                  (7,
                                    f/0),
                                [
                                  Variable
                                    (7,
                                      x/0)
                                ]),
                            Apply
                              (7,
                                Variable
                                  (7,
                                    map_coq_rec/0),
                                [
                                  Variable
                                    (7,
                                      l/0)
                                ])))
                    ]))
            ]) in
        Apply (8, Variable (8, map_coq_rec/0), [ Variable (8, l/0) ]))
    ])

10
Value
  (non_rec, @.,
    [
      ((map2, [ A; B ], [ (f, (A -> B)); (l, Type (list/1, A)) ],
        Some Type (list/1, B)),
        LetFun 11
          (rec, @coq_rec,
            [
              ((map2_coq_rec, [ C; D ],
                [ (f, (C -> D)); (l, Type (list/1, C)) ],
                Some Type (list/1, D)),
                Match
                  (12,
                    Variable
                      (12,
                        l/0),
                    [
                      (Constructor
                        ([]/1),
                        Constructor
                          (13,
                            []/1));
                      (Constructor
                        (cons/1,
                          x,
                          l),
                        Constructor
                          (14,
                            cons/1,
                            Apply
                              (14,
                                Variable
                                  (14,
                                    f/0),
                                [
                                  Variable
                                    (14,
                                      x/0)
                                ]),
                            Apply
                              (14,
                                Variable
                                  (14,
                                    map2_coq_rec/0),
                                [
                                  Variable
                                    (14,
                                      f/0);
                                  Variable
                                    (14,
                                      l/0)
                                ])))
                    ]))
            ]) in
        Apply
          (15, Variable (15, map2_coq_rec/0),
            [ Variable (15, f/0); Variable (15, l/0) ]))
    ])
