3
Value
  (rec,
    [
      ((odd_length, [ A ], [ (l, Type (list/1, A)) ], Some Type (bool/1)),
        Match
          (4, Variable (4, l/0),
            [
              (Constructor ([]/1), Constructor (5, false/1));
              (Constructor (cons/1, Any, l),
                Apply
                  (6,
                    Variable
                      (6,
                        negb/1),
                    [
                      Apply
                        (6,
                          Variable
                            (6,
                              even_length/0),
                          [
                            Variable
                              (6,
                                l/0)
                          ])
                    ]))
            ]));
      ((even_length, [ A ], [ (l, Type (list/1, A)) ], Some Type (bool/1)),
        Match
          (9, Variable (9, l/0),
            [
              (Constructor ([]/1), Constructor (10, true/1));
              (Constructor (cons/1, Any, l),
                Apply
                  (11,
                    Variable
                      (11,
                        negb/1),
                    [
                      Apply
                        (11,
                          Variable
                            (11,
                              odd_length/0),
                          [
                            Variable
                              (11,
                                l/0)
                          ])
                    ]))
            ]))
    ])
