((Value
  ((is_rec (New true))
   (cases
    ((((name odd_length) (typ_vars (A))
       (args
        ((l
          (Apply ((path_name ((path ()) (base list))) (depth 1))
           ((Variable A))))))
       (typ ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))
      (Match (Variable ((path_name ((path ()) (base l))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base []))) (depth 1)) ())
         (Constructor ((path_name ((path ()) (base false))) (depth 1)) ()))
        ((Constructor ((path_name ((path ()) (base cons))) (depth 1))
          (Any (Variable l)))
         (Apply (Variable ((path_name ((path ()) (base negb))) (depth 1)))
          ((Apply
            (Variable ((path_name ((path ()) (base even_length))) (depth 0)))
            ((Variable ((path_name ((path ()) (base l))) (depth 0)))))))))))
     (((name even_length) (typ_vars (A))
       (args
        ((l
          (Apply ((path_name ((path ()) (base list))) (depth 1))
           ((Variable A))))))
       (typ ((Apply ((path_name ((path ()) (base bool))) (depth 1)) ()))))
      (Match (Variable ((path_name ((path ()) (base l))) (depth 0)))
       (((Constructor ((path_name ((path ()) (base []))) (depth 1)) ())
         (Constructor ((path_name ((path ()) (base true))) (depth 1)) ()))
        ((Constructor ((path_name ((path ()) (base cons))) (depth 1))
          (Any (Variable l)))
         (Apply (Variable ((path_name ((path ()) (base negb))) (depth 1)))
          ((Apply
            (Variable ((path_name ((path ()) (base odd_length))) (depth 0)))
            ((Variable ((path_name ((path ()) (base l))) (depth 0))))))))))))))))
