((Module M
  ((Value
    ((is_rec (New false))
     (cases
      ((((name n) (typ_vars ()) (args ())
         (typ ((Apply ((path ()) (base Z)) ()))))
        (Constant (Int 12)))))))))
 (Module N
  ((Value
    ((is_rec (New false))
     (cases
      ((((name n) (typ_vars ()) (args ())
         (typ ((Apply ((path ()) (base bool)) ()))))
        (Constructor ((path ()) (base true)) ()))))))
   (Value
    ((is_rec (New false))
     (cases
      ((((name x) (typ_vars ()) (args ())
         (typ ((Apply ((path ()) (base bool)) ()))))
        (Variable ((path ()) (base n))))))))
   (Open (M))
   (Value
    ((is_rec (New false))
     (cases
      ((((name y) (typ_vars ()) (args ())
         (typ ((Apply ((path ()) (base Z)) ()))))
        (Variable ((path (M)) (base n))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name b) (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base bool)) ()))))
      (Variable ((path (N)) (base n))))))))
 (Open (N))
 (Value
  ((is_rec (New false))
   (cases
    ((((name b') (typ_vars ()) (args ())
       (typ ((Apply ((path ()) (base bool)) ()))))
      (Variable ((path (N)) (base n)))))))))
