((Module
  (Known ((file_name tests/ex31.ml) (line 3))
   ((file_name tests/ex31.ml) (line 8)))
  M
  ((Value
    (Known ((file_name tests/ex31.ml) (line 6))
     ((file_name tests/ex31.ml) (line 6)))
    ((is_rec (New false))
     (cases
      ((((name b) (typ_vars ()) (args ())
         (typ ((Apply ((path_name ((path ()) (base bool))) (depth 2)) ()))))
        (Constructor ((path_name ((path ()) (base false))) (depth 2)) ()))))))
   (Value
    (Known ((file_name tests/ex31.ml) (line 7))
     ((file_name tests/ex31.ml) (line 7)))
    ((is_rec (New false))
     (cases
      ((((name n) (typ_vars ()) (args ())
         (typ ((Apply ((path_name ((path ()) (base Z))) (depth 2)) ()))))
        (Constant (Int 12)))))))))
 (Value
  (Known ((file_name tests/ex31.ml) (line 10))
   ((file_name tests/ex31.ml) (line 10)))
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars ()) (args ())
       (typ ((Apply ((path_name ((path ()) (base Z))) (depth 1)) ()))))
      (Apply (Variable ((path_name ((path (Z)) (base add))) (depth 1)))
       ((Variable ((path_name ((path (M)) (base n))) (depth 0)))
        (Constant (Int 2))))))))))
