3 Signature IM1:
  4 (Value (n, [ ], Type (Z/2)))
  
  5 (Value (f, [ a; b ], (a -> (a * b))))
  
  7
  Inductive t1:
    ([ a ], [ (C1, [ Type (Z/2) ]); (C2, [ a; Type (bool/2) ]) ])
  
  11
  Record t2:
    [ (f1, Type (Z/2)); (f2, Type (bool/2)) ]
  
  15 Synonym (t3, [ a ], (Type (Z/2) * a))
  
  17 Abstract (t4, [ ])
  
  19 Abstract (t5, [ a; b ])

22 Signature IM2:
  23 Abstract (t, [ ])
  
  24 (Value (m, [ ], Type (Z/2)))
  
  25 (Value (b, [ ], Type (t/0)))

28 Module M2:
  29
  Value
    (non_rec, @.,
      [
        ((null, [ ], [ ], Some (Type (Z/2) * Type (bool/2))),
          Tuple (29, Constant (29, Int(0)), Constructor (29, false/2)))
      ])
  
  30 Synonym (t, [ ], Type (bool/2))
  
  31
  Value
    (non_rec, @., [ ((m, [ ], [ ], Some Type (Z/2)), Constant (31, Int(12))) ])
  
  32
  Value
    (non_rec, @.,
      [ ((b, [ ], [ ], Some Type (bool/2)), Constructor (32, false/2)) ])
