((Value
  ((is_rec (New false))
   (cases
    ((((name map) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Variable B)))
         (l (Apply (PathName ((path ()) (base list))) ((Variable A))))))
       (typ ((Apply (PathName ((path ()) (base list))) ((Variable B))))))
      (LetFun
       ((is_rec (New true))
        (cases
         ((((name map_coq_rec) (typ_vars ())
            (args
             ((l (Apply (PathName ((path ()) (base list))) ((Variable A))))))
            (typ ((Apply (PathName ((path ()) (base list))) ((Variable B))))))
           (Match (Variable (PathName ((path ()) (base l))))
            (((Constructor ((path ()) (base [])) ())
              (Constructor ((path ()) (base [])) ()))
             ((Constructor ((path ()) (base cons))
               ((Variable x) (Variable l)))
              (Constructor ((path ()) (base cons))
               ((Apply (Variable (PathName ((path ()) (base f))))
                 ((Variable (PathName ((path ()) (base x))))))
                (Apply (Variable (PathName ((path ()) (base map_coq_rec))))
                 ((Variable (PathName ((path ()) (base l))))))))))
            ())))))
       (Apply (Variable (PathName ((path ()) (base map_coq_rec))))
        ((Variable (PathName ((path ()) (base l))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name map2) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Variable B)))
         (l (Apply (PathName ((path ()) (base list))) ((Variable A))))))
       (typ ((Apply (PathName ((path ()) (base list))) ((Variable B))))))
      (LetFun
       ((is_rec (New true))
        (cases
         ((((name map2_coq_rec) (typ_vars (C D))
            (args
             ((f (Arrow (Variable C) (Variable D)))
              (l (Apply (PathName ((path ()) (base list))) ((Variable C))))))
            (typ ((Apply (PathName ((path ()) (base list))) ((Variable D))))))
           (Match (Variable (PathName ((path ()) (base l))))
            (((Constructor ((path ()) (base [])) ())
              (Constructor ((path ()) (base [])) ()))
             ((Constructor ((path ()) (base cons))
               ((Variable x) (Variable l)))
              (Constructor ((path ()) (base cons))
               ((Apply (Variable (PathName ((path ()) (base f))))
                 ((Variable (PathName ((path ()) (base x))))))
                (Apply (Variable (PathName ((path ()) (base map2_coq_rec))))
                 ((Variable (PathName ((path ()) (base f))))
                  (Variable (PathName ((path ()) (base l))))))))))
            ())))))
       (Apply (Variable (PathName ((path ()) (base map2_coq_rec))))
        ((Variable (PathName ((path ()) (base f))))
         (Variable (PathName ((path ()) (base l)))))))))))))
