((Value
  ((is_rec (New false))
   (cases
    ((((name f) (typ_vars ())
       (args
        ((n (Apply (PathName ((path ()) (base Z))) ()))
         (b (Apply (PathName ((path ()) (base bool))) ()))))
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (IfThenElse (Variable (PathName ((path ()) (base b))))
       (Apply (Variable (PathName ((path (Z)) (base add))))
        ((Variable (PathName ((path ()) (base n)))) (Constant (Int 1))))
       (Apply (Variable (PathName ((path (Z)) (base sub))))
        ((Variable (PathName ((path ()) (base n)))) (Constant (Int 1)))))))))))
