((TypeDefinition
  (Inductive
   ((notations ())
    (typs
     ((gre (a) ()
       (((constructor_name Arg) (param_typs ((Variable a)))
         (res_typ_params ((Variable a))) (typ_vars ())))))))))
 (TypeDefinition
  (Inductive
   ((notations ())
    (typs
     ((foo () (a b)
       (((constructor_name Bar)
         (param_typs
          ((Variable a) (Apply (PathName ((path ()) (base Z))) ())
           (Variable b) (Variable c)))
         (res_typ_params
          ((Variable b) (Apply (PathName ((path ()) (base string))) ())))
         (typ_vars (a b c)))
        ((constructor_name Other)
         (param_typs ((Apply (PathName ((path ()) (base Z))) ())))
         (res_typ_params ((Variable a) (Variable b))) (typ_vars (a b))))))))))
 (TypeDefinition
  (Inductive
   ((notations ())
    (typs
     ((expr () (a)
       (((constructor_name Int)
         (param_typs ((Apply (PathName ((path ()) (base Z))) ())))
         (res_typ_params ((Apply (PathName ((path ()) (base Z))) ())))
         (typ_vars ()))
        ((constructor_name String)
         (param_typs ((Apply (PathName ((path ()) (base string))) ())))
         (res_typ_params ((Apply (PathName ((path ()) (base string))) ())))
         (typ_vars ()))
        ((constructor_name Sum)
         (param_typs
          ((Apply (PathName ((path ()) (base expr)))
            ((Apply (PathName ((path ()) (base Z))) ())))
           (Apply (PathName ((path ()) (base expr)))
            ((Apply (PathName ((path ()) (base Z))) ())))))
         (res_typ_params ((Apply (PathName ((path ()) (base Z))) ())))
         (typ_vars ()))
        ((constructor_name Pair)
         (param_typs
          ((Apply (PathName ((path ()) (base expr))) ((Variable a)))
           (Apply (PathName ((path ()) (base expr))) ((Variable b)))))
         (res_typ_params ((Tuple ((Variable a) (Variable b)))))
         (typ_vars (a b))))))))))
 (Value
  ((is_rec (New true))
   (cases
    ((((name proj_int) (typ_vars ())
       (args
        ((e
          (Apply (PathName ((path ()) (base expr)))
           ((Apply (PathName ((path ()) (base Z))) ()))))))
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Match (Variable (PathName ((path ()) (base e))))
       (((Constructor ((path ()) (base Int)) ((Variable n)))
         (Variable (PathName ((path ()) (base n)))))
        ((Constructor ((path ()) (base Sum)) ((Variable e1) (Variable e2)))
         (Apply (Variable (PathName ((path (Z)) (base add))))
          ((Apply (Variable (PathName ((path ()) (base proj_int))))
            ((Variable (PathName ((path ()) (base e1))))))
           (Apply (Variable (PathName ((path ()) (base proj_int))))
            ((Variable (PathName ((path ()) (base e2))))))))))
       ((Constant (Int 0))))))))))
