((TypeDefinition
  (Inductive
   ((gre (a)
     (((constructor_name Arg) (param_typs ((Variable a)))
       (res_typ (Apply (PathName ((path ()) (base gre))) ((Variable a))))
       (typ_vars (a))))))))
 (TypeDefinition
  (Inductive
   ((foo (a b)
     (((constructor_name Bar)
       (param_typs
        ((Variable a) (Apply (PathName ((path ()) (base Z))) ()) (Variable b)
         (Variable c)))
       (res_typ
        (Apply (PathName ((path ()) (base foo)))
         ((Variable b) (Apply (PathName ((path ()) (base string))) ()))))
       (typ_vars (a b c)))
      ((constructor_name Other)
       (param_typs ((Apply (PathName ((path ()) (base Z))) ())))
       (res_typ
        (Apply (PathName ((path ()) (base foo))) ((Variable a) (Variable b))))
       (typ_vars (a b))))))))
 (TypeDefinition
  (Inductive
   ((expr (a)
     (((constructor_name Int) (param_typs ())
       (res_typ
        (Apply (PathName ((path ()) (base expr)))
         ((Apply (PathName ((path ()) (base Z))) ()))))
       (typ_vars ()))
      ((constructor_name String) (param_typs ())
       (res_typ
        (Apply (PathName ((path ()) (base expr)))
         ((Apply (PathName ((path ()) (base string))) ()))))
       (typ_vars ()))
      ((constructor_name Sum)
       (param_typs
        ((Apply (PathName ((path ()) (base expr)))
          ((Apply (PathName ((path ()) (base Z))) ())))
         (Apply (PathName ((path ()) (base expr)))
          ((Apply (PathName ((path ()) (base Z))) ())))))
       (res_typ
        (Apply (PathName ((path ()) (base expr)))
         ((Apply (PathName ((path ()) (base Z))) ()))))
       (typ_vars ()))
      ((constructor_name Pair)
       (param_typs
        ((Apply (PathName ((path ()) (base expr))) ((Variable a)))
         (Apply (PathName ((path ()) (base expr))) ((Variable b)))))
       (res_typ
        (Apply (PathName ((path ()) (base expr)))
         ((Tuple ((Variable a) (Variable b))))))
       (typ_vars (a b)))))))))
