((Value
  ((is_rec (New false))
   (cases
    ((((name n1) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (LetVar m (Constant (Int 12))
       (LetVar n1 (Variable (PathName ((path ()) (base m))))
        (Variable (PathName ((path ()) (base n1)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n2) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (LetFun
       ((is_rec (New false))
        (cases
         ((((name p1) (typ_vars (A B C))
            (args
             ((c
               (Arrow (Arrow (Variable A) (Arrow (Variable B) (Variable A)))
                (Variable C)))))
            (typ ((Variable C))))
           (Apply (Variable (PathName ((path ()) (base c))))
            ((Function x
              (Function y (Variable (PathName ((path ()) (base x))))))))))))
       (LetFun
        ((is_rec (New false))
         (cases
          ((((name c) (typ_vars (A))
             (args
              ((f
                (Arrow (Apply (PathName ((path ()) (base Z))) ())
                 (Arrow (Apply (PathName ((path ()) (base Z))) ())
                  (Variable A))))))
             (typ ((Variable A))))
            (Apply (Variable (PathName ((path ()) (base f))))
             ((Constant (Int 12)) (Constant (Int 23))))))))
        (Apply (Variable (PathName ((path ()) (base p1))))
         ((Variable (PathName ((path ()) (base c))))))))))))))
