((Module List2
  ((TypeDefinition
    (Inductive
     ((t (a) ()
       (((constructor_name Nil) (param_typs ())
         (res_typ_params ((Variable a))) (typ_vars ()))
        ((constructor_name Cons)
         (param_typs
          ((Variable a)
           (Apply (PathName ((path ()) (base t))) ((Variable a)))))
         (res_typ_params ((Variable a))) (typ_vars ())))))))
   (Value
    ((is_rec (New true))
     (cases
      ((((name sum) (typ_vars ())
         (args
          ((l
            (Apply (PathName ((path ()) (base t)))
             ((Apply (PathName ((path ()) (base Z))) ()))))))
         (typ ((Apply (PathName ((path ()) (base Z))) ()))))
        (Match (Variable (PathName ((path ()) (base l))))
         (((Constructor ((path ()) (base Nil)) ()) (Constant (Int 0)))
          ((Constructor ((path ()) (base Cons)) ((Variable x) (Variable xs)))
           (Apply (Variable (PathName ((path (Z)) (base add))))
            ((Variable (PathName ((path ()) (base x))))
             (Apply (Variable (PathName ((path ()) (base sum))))
              ((Variable (PathName ((path ()) (base xs))))))))))))))))
   (Value
    ((is_rec (New true))
     (cases
      ((((name of_list) (typ_vars (A))
         (args
          ((function_parameter
            (Apply (PathName ((path ()) (base list))) ((Variable A))))))
         (typ ((Apply (PathName ((path ()) (base t))) ((Variable A))))))
        (Match (Variable (PathName ((path ()) (base function_parameter))))
         (((Constructor ((path ()) (base [])) ())
           (Constructor ((path ()) (base Nil)) ()))
          ((Constructor ((path ()) (base cons)) ((Variable x) (Variable xs)))
           (Constructor ((path ()) (base Cons))
            ((Variable (PathName ((path ()) (base x))))
             (Apply (Variable (PathName ((path ()) (base of_list))))
              ((Variable (PathName ((path ()) (base xs))))))))))))))))
   (Module Inside
    ((Value
      ((is_rec (New false))
       (cases
        ((((name x) (typ_vars ()) (args ())
           (typ ((Apply (PathName ((path ()) (base Z))) ()))))
          (Constant (Int 12)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars (A)) (args ((function_parameter (Variable A))))
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Match (Variable (PathName ((path ()) (base function_parameter))))
       ((Any
         (Apply (Variable (PathName ((path (List2)) (base sum))))
          ((Apply (Variable (PathName ((path (List2)) (base of_list))))
            ((Constructor ((path ()) (base cons))
              ((Constant (Int 5))
               (Constructor ((path ()) (base cons))
                ((Constant (Int 7))
                 (Constructor ((path ()) (base cons))
                  ((Constant (Int 6))
                   (Constructor ((path ()) (base cons))
                    ((Variable (PathName ((path (List2 Inside)) (base x))))
                     (Constructor ((path ()) (base [])) ()))))))))))))))))))))))
