((Value
  ((is_rec (New false))
   (cases
    ((((name b) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base bool))) ()))))
      (Apply (Variable (PathName ((path ()) (base orb))))
       ((Apply (Variable (PathName ((path ()) (base equiv_decb))))
         ((Constructor ((path ()) (base false)) ())
          (Constructor ((path ()) (base true)) ())))
        (Apply (Variable (PathName ((path ()) (base andb))))
         ((Apply (Variable (PathName ((path ()) (base nequiv_decb))))
           ((Constructor ((path ()) (base tt)) ())
            (Constructor ((path ()) (base tt)) ())))
          (Apply (Variable (PathName ((path ()) (base negb))))
           ((Constructor ((path ()) (base true)) ()))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n1) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path (Z)) (base add))))
       ((Constant (Int 1))
        (Apply (Variable (PathName ((path (Z)) (base mul))))
         ((Constant (Int 2)) (Constant (Int 3)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n2) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path (Z)) (base sub))))
       ((Apply (Variable (PathName ((path (Z)) (base add))))
         ((Apply (Variable (PathName ((path (Z)) (base abs))))
           ((Constant (Int -1))))
          (Constant (Int 1))))
        (Apply (Variable (PathName ((path (Z)) (base mul))))
         ((Apply (Variable (PathName ((path (Z)) (base modulo))))
           ((Apply (Variable (PathName ((path (Z)) (base div))))
             ((Constant (Int 5)) (Constant (Int 23))))
            (Constant (Int 4))))
          (Constant (Int 3)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n3) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path (Z)) (base pred))))
       ((Apply (Variable (PathName ((path (Z)) (base succ))))
         ((Constant (Int 12)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n4) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path (Z)) (base lxor))))
       ((Apply (Variable (PathName ((path (Z)) (base lor))))
         ((Apply (Variable (PathName ((path (Z)) (base land))))
           ((Constant (Int 5)) (Constant (Int 7))))
          (Constant (Int 3))))
        (Constant (Int 9)))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n5) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path (Z)) (base add))))
       ((Apply (Variable (PathName ((path (Z)) (base shiftl))))
         ((Constant (Int 156)) (Constant (Int 4))))
        (Apply (Variable (PathName ((path (Z)) (base shiftr))))
         ((Constant (Int 12)) (Constant (Int 1)))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name s) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base string))) ()))))
      (Apply (Variable (PathName ((path (String)) (base append))))
       ((Constant (String ghj)) (Constant (String klm)))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name c) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply
       (Variable (PathName ((path (OCaml Pervasives)) (base int_of_char))))
       ((Constant (Char c)))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name x) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base unit))) ()))))
      (Apply (Variable (PathName ((path (OCaml Pervasives)) (base ignore))))
       ((Constant (Int 23)))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name p) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path (Z)) (base add))))
       ((Apply (Variable (PathName ((path ()) (base fst))))
         ((Tuple ((Constant (Int 1)) (Constant (Int 2))))))
        (Apply (Variable (PathName ((path ()) (base snd))))
         ((Tuple ((Constant (Int 3)) (Constant (Int 4)))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name l) (typ_vars ()) (args ())
       (typ
        ((Apply (PathName ((path ()) (base list)))
          ((Apply (PathName ((path ()) (base Z))) ()))))))
      (Apply (Variable (PathName ((path (OCaml Pervasives)) (base app))))
       ((Constructor ((path ()) (base cons))
         ((Constant (Int 1))
          (Constructor ((path ()) (base cons))
           ((Constant (Int 2)) (Constructor ((path ()) (base [])) ())))))
        (Constructor ((path ()) (base cons))
         ((Constant (Int 3)) (Constructor ((path ()) (base [])) ()))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name y) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path ()) (base apply))))
       ((Function n
         (Apply (Variable (PathName ((path (Z)) (base add))))
          ((Variable (PathName ((path ()) (base n)))) (Constant (Int 1)))))
        (Constant (Int 12))))))))))
