((Value
  ((is_rec (New false))
   (cases
    ((((name u) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base unit))) ()))))
      (Constructor ((path ()) (base tt)) ()))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name l1) (typ_vars (A)) (args ())
       (typ ((Apply (PathName ((path ()) (base list))) ((Variable A))))))
      (Constructor ((path ()) (base [])) ()))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name l2) (typ_vars ()) (args ())
       (typ
        ((Apply (PathName ((path ()) (base list)))
          ((Apply (PathName ((path ()) (base Z))) ()))))))
      (Constructor ((path ()) (base cons))
       ((Constant (Int 1)) (Constructor ((path ()) (base [])) ()))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name l3) (typ_vars ()) (args ())
       (typ
        ((Apply (PathName ((path ()) (base list)))
          ((Apply (PathName ((path ()) (base Z))) ()))))))
      (Constructor ((path ()) (base cons))
       ((Constant (Int 1))
        (Constructor ((path ()) (base cons))
         ((Constant (Int 5))
          (Constructor ((path ()) (base cons))
           ((Constant (Int 7))
            (Constructor ((path ()) (base cons))
             ((Constant (Int 32))
              (Constructor ((path ()) (base cons))
               ((Constant (Int 15)) (Constructor ((path ()) (base [])) ()))))))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name o1) (typ_vars (A)) (args ())
       (typ ((Apply (PathName ((path ()) (base option))) ((Variable A))))))
      (Constructor ((path ()) (base None)) ()))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name o2) (typ_vars ()) (args ())
       (typ
        ((Apply (PathName ((path ()) (base option)))
          ((Apply (PathName ((path ()) (base Z))) ()))))))
      (Constructor ((path ()) (base Some)) ((Constant (Int 12)))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name c) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base ascii))) ()))))
      (Constant (Char g)))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name s1) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base string))) ()))))
      (Constant (String bla)))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name s2) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base string))) ()))))
      (Constant (String "\""))))))))
