((Value
  ((is_rec (New true))
   (cases
    ((((name map) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Variable B)))
         (l (Apply (PathName ((path ()) (base list))) ((Variable A))))))
       (typ ((Apply (PathName ((path ()) (base list))) ((Variable B))))))
      (Match (Variable (PathName ((path ()) (base l))))
       (((Constructor ((path ()) (base [])) ())
         (Constructor ((path ()) (base [])) ()))
        ((Constructor ((path ()) (base cons)) ((Variable x) (Variable xs)))
         (Constructor ((path ()) (base cons))
          ((Apply (Variable (PathName ((path ()) (base f))))
            ((Variable (PathName ((path ()) (base x))))))
           (Apply (Variable (PathName ((path ()) (base map))))
            ((Variable (PathName ((path ()) (base f))))
             (Variable (PathName ((path ()) (base xs))))))))))
       ()))))))
 (Value
  ((is_rec (New true))
   (cases
    ((((name fold) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Arrow (Variable B) (Variable A))))
         (a (Variable A))
         (l (Apply (PathName ((path ()) (base list))) ((Variable B))))))
       (typ ((Variable A))))
      (Match (Variable (PathName ((path ()) (base l))))
       (((Constructor ((path ()) (base [])) ())
         (Variable (PathName ((path ()) (base a)))))
        ((Constructor ((path ()) (base cons)) ((Variable x) (Variable xs)))
         (Apply (Variable (PathName ((path ()) (base fold))))
          ((Variable (PathName ((path ()) (base f))))
           (Apply (Variable (PathName ((path ()) (base f))))
            ((Variable (PathName ((path ()) (base a))))
             (Variable (PathName ((path ()) (base x))))))
           (Variable (PathName ((path ()) (base xs))))))))
       ()))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name l) (typ_vars ()) (args ())
       (typ
        ((Apply (PathName ((path ()) (base list)))
          ((Apply (PathName ((path ()) (base Z))) ()))))))
      (Constructor ((path ()) (base cons))
       ((Constant (Int 5))
        (Constructor ((path ()) (base cons))
         ((Constant (Int 6))
          (Constructor ((path ()) (base cons))
           ((Constant (Int 7))
            (Constructor ((path ()) (base cons))
             ((Constant (Int 2)) (Constructor ((path ()) (base [])) ()))))))))))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars (A))
       (args
        ((incr
          (Arrow (Apply (PathName ((path ()) (base Z))) ()) (Variable A)))
         (plus
          (Arrow (Apply (PathName ((path ()) (base Z))) ())
           (Arrow (Variable A) (Apply (PathName ((path ()) (base Z))) ()))))))
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (Apply (Variable (PathName ((path ()) (base fold))))
       ((Function x
         (Function y
          (Apply (Variable (PathName ((path ()) (base plus))))
           ((Variable (PathName ((path ()) (base x))))
            (Variable (PathName ((path ()) (base y))))))))
        (Constant (Int 0))
        (Apply (Variable (PathName ((path ()) (base map))))
         ((Variable (PathName ((path ()) (base incr))))
          (Variable (PathName ((path ()) (base l))))))))))))))
