((Value
  ((is_rec (New true))
   (cases
    ((((name f_map) (typ_vars (A B))
       (args
        ((f (Arrow (Variable A) (Variable B)))
         (l (Apply (PathName ((path ()) (base list))) ((Variable A))))))
       (typ ((Apply (PathName ((path ()) (base list))) ((Variable B))))))
      (Match (Variable (PathName ((path ()) (base l))))
       (((Constructor ((path ()) (base [])) ())
         (Constructor ((path ()) (base [])) ()))
        ((Constructor ((path ()) (base cons)) ((Variable x) (Variable l)))
         (Constructor ((path ()) (base cons))
          ((Apply (Variable (PathName ((path ()) (base f))))
            ((Variable (PathName ((path ()) (base x))))))
           (Apply (Variable (PathName ((path ()) (base f_map))))
            ((Variable (PathName ((path ()) (base f))))
             (Variable (PathName ((path ()) (base l))))))))))
       ()))))))
 (Value
  ((is_rec (New false))
   (cases
    ((((name n) (typ_vars ()) (args ())
       (typ ((Apply (PathName ((path ()) (base Z))) ()))))
      (LetFun
       ((is_rec (New true))
        (cases
         ((((name sum) (typ_vars ())
            (args
             ((l
               (Apply (PathName ((path ()) (base list)))
                ((Apply (PathName ((path ()) (base Z))) ()))))))
            (typ ((Apply (PathName ((path ()) (base Z))) ()))))
           (Match (Variable (PathName ((path ()) (base l))))
            (((Constructor ((path ()) (base [])) ()) (Constant (Int 0)))
             ((Constructor ((path ()) (base cons))
               ((Variable x) (Variable l)))
              (Apply (Variable (PathName ((path (Z)) (base add))))
               ((Variable (PathName ((path ()) (base x))))
                (Apply (Variable (PathName ((path ()) (base sum))))
                 ((Variable (PathName ((path ()) (base l))))))))))
            ())))))
       (Apply (Variable (PathName ((path ()) (base sum))))
        ((Constructor ((path ()) (base cons))
          ((Constant (Int 1))
           (Constructor ((path ()) (base cons))
            ((Constant (Int 2))
             (Constructor ((path ()) (base cons))
              ((Constant (Int 3)) (Constructor ((path ()) (base [])) ()))))))))))))))))
