(** Generated by coq-of-ocaml *)
Require Import OCaml.OCaml.

Set Primitive Projections.
Set Printing Projections.
Open Scope string_scope.
Open Scope Z_scope.
Open Scope type_scope.
Import ListNotations.

Definition t1 : Set := string.

Definition t2 (a b : Set) : Set := a * b.
